In [1]:
import pandas as pd
from tkinter import *
from tkinter import filedialog
from tkinter.font import Font
import os
#import for writing Imed Report in Excel Sheet
import openpyxl as opxl
from random import random

In [2]:
def makeDframe(packagelist):
    df=pd.DataFrame()
    df['Package']=packagelist
    df[1]=0
    df[2]=0
    df[3]=0
    df[4]=0
    df[5]=0
    df[6]=0
    df[7]=0
    df[8]=0
    df[9]=0
    df[10]=0
    df[11]=0
    df[12]=0
    df[13]=0
    return df

def writeDataframe(wbpath,df,sheetname):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]
    offset=2
    for index,row in df.iterrows():        
        myrow=index+offset
        wsheet.cell(row=myrow,column=2).value=row[1]
        wsheet.cell(row=myrow,column=3).value=row[2]
        wsheet.cell(row=myrow,column=4).value=row[3]
        wsheet.cell(row=myrow,column=5).value=row[4]
        wsheet.cell(row=myrow,column=6).value=row[5]
        wsheet.cell(row=myrow,column=7).value=row[6]
        wsheet.cell(row=myrow,column=8).value=row[7]
        wsheet.cell(row=myrow,column=9).value=row[8]
        wsheet.cell(row=myrow,column=10).value=row[9]
        wsheet.cell(row=myrow,column=11).value=row[10]
        wsheet.cell(row=myrow,column=12).value=row[11]
        wsheet.cell(row=myrow,column=13).value=row[12]
        wsheet.cell(row=myrow,column=14).value=row[13]
    wb.save(wbpath)
    
def aggregateQuantity(packagelist,detail_df):
    columnname=['1','2','3','4','5','6','7','8','9','10','11','12','13']
    columnindex=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    aggregate_df=makeDframe(packagelist)
    for index,row in detail_df.iterrows():
        print(index)
        i=packagelist.index(row['Package'])
        stname=int(row['Structure Code'])        
        aggregate_df.iloc[i,stname]=float(aggregate_df.iloc[i,stname])+float(row['Qnty'])
    return aggregate_df

def aggregateCost(packagelist,detail_df):
    columnname=['1','2','3','4','5','6','7','8','9','10','11','12','13']                                                                   
    columnindex=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    aggregate_df=makeDframe(packagelist)
    for index,row in detail_df.iterrows():        
        print(index)
        i=packagelist.index(row['Package'])
        stname=int(row['Structure Code'])    
        aggregate_df.iloc[i,stname]=float(aggregate_df.iloc[i,stname])+float(row['Cost'])
    return aggregate_df

def writeDataframe3(wbpath,df,sheetname,dfcols,xlcols,offset):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]    
    for index,row in df.iterrows():        
        myrow=index+offset
        for idf,ixl in zip(dfcols,xlcols):
            wsheet.cell(row=myrow,column=ixl).value=row[idf]               
    wb.save(wbpath)
    
def writeDataframe2(wbpath,df,sheetname):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]
    offset=2
    for index,row in df.iterrows():        
        myrow=index+offset
        wsheet.cell(row=myrow,column=1).value=row[0]
        wsheet.cell(row=myrow,column=2).value=row[1]
        wsheet.cell(row=myrow,column=3).value=row[2]
        wsheet.cell(row=myrow,column=4).value=row[3]
        wsheet.cell(row=myrow,column=5).value=row[4]
        wsheet.cell(row=myrow,column=6).value=row[5]        
    wb.save(wbpath)
def aggregateWorksHaorWise(input_df,output_df,haor_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[10]
        stcode=int(row[8])
        ri=haor_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[3])           
    return output_df

def aggregateCostHaorWise(input_df,output_df,haor_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[10]
        stcode=int(row[8])
        ri=haor_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[4])           
    return output_df
def aggregateWorksPackageWise(input_df,output_df,haor_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[6]
        stcode=int(row[8])
        ri=haor_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[3])           
    return output_df

def aggregateCostPackageWise(input_df,output_df,haor_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[6]
        stcode=int(row[8])
        ri=haor_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[4])           
    return output_df

def writeDataframe5(wbpath,df,sheetname,dfcols,xlcols,rowindex):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]
    offset=2
    for index,row in df.iterrows():        
        myrow=index+offset
        wsheet.cell(row=myrow,column=1).value=row[0]
        wsheet.cell(row=myrow,column=2).value=row[1]
        wsheet.cell(row=myrow,column=3).value=row[2]
        wsheet.cell(row=myrow,column=4).value=row[3]
        wsheet.cell(row=myrow,column=5).value=row[4]
        wsheet.cell(row=myrow,column=6).value=row[5]        
    wb.save(wbpath)
def initializeCostDFToZero(output_df):
    for index,row in output_df.iterrows():
        for i in range (2,14):
            output_df.iloc[index,i]=0
    return output_df
def aggrgateCostByStructureCode(input_df,output_df,stcodes):
    for index,row in input_df.iterrows():
        #print(row)
        code=int(row[8])
        #stcode=int(row[8])
        #ri=haor_list.index(code)
        #ci=stcode+1
        #cost
        if code-1==16:            
            output_df.iloc[code-1,5]=float(output_df.iloc[code-1,5])+float(row[4])            
            output_df.iloc[code-1,8]=float(output_df.iloc[code-1,8])+float(row[4])      
        else:
            output_df.iloc[code-1,5]=float(output_df.iloc[code-1,5])+float(row[4])*0.1400
            output_df.iloc[code-1,6]=float(output_df.iloc[code-1,6])+float(row[4])*0.8600
            output_df.iloc[code-1,8]=float(output_df.iloc[code-1,8])+float(row[4])           
        #quantity
        output_df.iloc[code-1,4]=float(output_df.iloc[code-1,4])+float(row[3]) 
    return output_df
def transferStructureCostToDPPCost(input_df,output_df):
    n=output_df.shape[0]
    myvalue=[0 for i in range(0,n)]
    output_df.iloc[:,4]=myvalue
    output_df.iloc[:,5]=myvalue
    output_df.iloc[:,6]=myvalue
    output_df.iloc[:,7]=myvalue
    output_df.iloc[:,8]=myvalue
    output_df.iloc[:,9]=myvalue
    for index,row in input_df.iterrows():
        r1=row[2]-1
        #print("row={}".format(r1))
        #print(row[4])
        output_df.iloc[r1,4]=output_df.iloc[r1,4]+row[4]
        output_df.iloc[r1,5]=output_df.iloc[r1,5]+row[5]
        output_df.iloc[r1,6]=output_df.iloc[r1,6]+row[6]
    output_df.iloc[:,8]=output_df.iloc[:,5]+output_df.iloc[:,6]+output_df.iloc[:,7]
    return output_df
def transferStructureCostToDPPCost2(input_df,output_df):
    #n=civil_works_cost_df.shape[0]
    #myvalue=[0 for i in range(0,n)]
    #output_df.iloc[:,4]=myvalue
    #output_df.iloc[:,5]=myvalue
    #output_df.iloc[:,6]=myvalue
    for index,row in input_df.iterrows():
        r1=row[2]-1
        #print("row={}".format(r1))
        #print(row[4])
        output_df.iloc[r1,4]=output_df.iloc[r1,4]+row[4]
        output_df.iloc[r1,5]=output_df.iloc[r1,5]+row[5]
        output_df.iloc[r1,6]=output_df.iloc[r1,6]+row[6]
    return output_df
def makeDFforSec8(first_data,rvised_data,quantity):
    mydf=pd.DataFrame()
    ecode=list(rvised_data['Code'])
    description=list(rvised_data['Description'])
    cmpindex=list(rvised_data['rindex'])
    annexindex=list(rvised_data['annex_index'])
    itemunits=list(quantity['U1'])
    mydf=mydf.assign(Code=ecode,Description=description,rindex=cmpindex,annex_index=annexindex,units=itemunits)       
    q=list(quantity['Q1'])
    gob=list(first_data['GOB'])
    rpa=list(first_data['RPA'])
    dpa=list(first_data['DPA'])
    mydf['QUANTITY_1stRevised']=q
    mydf['GOB_1stRevised']=gob
    mydf['RPA_1stRevised']=rpa
    mydf['DPA_1stRevised']=dpa
    mydf['TOTAL_1stRevised']=mydf['GOB_1stRevised']+mydf['RPA_1stRevised']+ mydf['DPA_1stRevised']  
    q=list(quantity['Q2'])
    gob=list(rvised_data['GOB'])
    rpa=list(rvised_data['RPA'])
    dpa=list(rvised_data['DPA'])
    mydf['QUANTITY_2ndRevised']=q
    mydf['GOB_2ndRevised']=gob
    mydf['RPA_2ndRevised']=rpa
    mydf['DPA_2ndRevised']=dpa
    mydf['TOTAL_2ndRevised']=mydf['GOB_2ndRevised']+mydf['RPA_2ndRevised']+ mydf['DPA_2ndRevised']
    mydf['Diff_Q']=0
    mydf['Diff_GOB']=mydf['GOB_2ndRevised']-mydf['GOB_1stRevised']
    mydf['Diff_RPA']=mydf['RPA_2ndRevised']-mydf['RPA_1stRevised']
    mydf['Diff_DPA']=mydf['DPA_2ndRevised']-mydf['DPA_1stRevised']
    mydf['Diff_TOTAL']=mydf['TOTAL_2ndRevised']-mydf['TOTAL_1stRevised']
    """ 
    mydf=mydf.assign(QUANTITY_2ndRevised=q,GOB_2ndRevised=gob,RPA_2ndRevised=rpa,DPA_2ndRevised=dpa,TOTAL_2ndRevised=0)
    mydf['TOTAL_2ndRevised']=mydf['GOB_2ndRevised']+mydf['RPA_2ndRevised']+mydf['DPA_2ndRevised']   
    mydf=mydf.assign(Diff_Q=0,Diff_GOB=0,Diff_RPA=0,Diff_DPA=0,Diff_TOTAL=0)
    mydf['Diff_GOB']=mydf['GOB_2ndRevised']-mydf['GOB_1stRevised']
    mydf['Diff_RPA']=mydf['RPA_2ndRevised']-mydf['RPA_1stRevised']
    mydf['Diff_DPA']=mydf['DPA_2ndRevised']-mydf['DPA_1stRevised']
    mydf['Diff_TOTAL']=mydf['TOTAL_2ndRevised']-mydf['TOTAL_1stRevised']
    """
    return mydf
def aggregateWorksDistricWise(input_df,output_df,district_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[11]
        stcode=int(row[8])
        ri=district_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[3])           
    return output_df

def aggregateCostDistrictWise(input_df,output_df,district_list):    
    for index,row in input_df.iterrows():
        #print(row)
        code=row[11]
        stcode=int(row[8])
        ri=district_list.index(code)
        ci=stcode+1                    
        output_df.iloc[ri,ci]=float(output_df.iloc[ri,ci])+float(row[4])
    output_df.iloc[:,19]=output_df.iloc[:,2]+output_df.iloc[:,3]+output_df.iloc[:,4]+\
    output_df.iloc[:,5]+output_df.iloc[:,6]+output_df.iloc[:,8]+output_df.iloc[:,9]+\
    output_df.iloc[:,10]+output_df.iloc[:,11]+output_df.iloc[:,12]+output_df.iloc[:,13]+\
    output_df.iloc[:,14]+output_df.iloc[:,15]+output_df.iloc[:,16]+output_df.iloc[:,17]+\
    output_df.iloc[:,18]
    
    return output_df
   
    
def applyRPACorrections(sec8_total_df):
    rpa1st=sum(list(sec8_total_df['RPA_1st']))
    rpa2nd=sum(list(sec8_total_df['RPA_2nd']))
    corrections=rpa2nd-rpa1st
    sec8_total_df.iloc[63,9]=sec8_total_df.iloc[63,9]+corrections
    sec8_total_df.iloc[63,10]=sec8_total_df.iloc[63,10]-corrections
    return sec8_total_df
def addQuantity(sec8_total_df,quantity_df):    
    sec8_total_df['Quantity_1st']=quantity_df['Q1']
    sec8_total_df['Quantity_2nd']=quantity_df['Q2']
    sec8_total_df['Quantity_diff']=quantity_df['Q3']
    sec8_total_df['units']=quantity_df['U1']
    return sec8_total_df
def calculateDifference(mydf):
    #GOB_Diff 	RPA_diff 	DPA_diff 	TOTAL_diff 	Tindex
    mydf['GOB_Diff']=mydf['GOB_2nd']-mydf['GOB_1st']
    mydf['RPA_diff']=mydf['RPA_2nd']-mydf['RPA_1st']
    mydf['DPA_diff']=mydf['DPA_2nd']-mydf['DPA_1st']
    mydf['TOTAL_diff']=mydf['GOB_Diff']+mydf['RPA_diff']+mydf['DPA_diff']  
    return mydf
def addRevisedCost(input_df,output_df):    
    gob=list(input_df['GOB'])
    rpa=list(input_df['RPA'])
    dpa=list(input_df['DPA'])
    total=list(input_df['TOTAL'])
    output_df['GOB_2nd']= gob
    output_df['RPA_2nd']=rpa
    output_df['DPA_2nd']=dpa
    output_df['TOTAL_2nd']=total
    #GOB_2nd	RPA_2nd	DPA_2nd	TOTAL_2nd
    return output_df
def calcualteUnitCost(input_df):
    nounitcost=[69,68,67,63,48,24]
    civilworks=[54,55,56,57,58,59,60,61,62,63,64,65,66]
    equipments=[41,42,43,44,45,47,49,50,51,52]
    for index,row in input_df.iterrows():
        if index in nounitcost:
            input_df.iloc[index,21]=0
        elif index in civilworks:
            input_df.iloc[index,21]=round(input_df.iloc[index,12]/input_df.iloc[index,8],2)
        elif index in equipments:
            input_df.iloc[index,21]=round(input_df.iloc[index,12]/input_df.iloc[index,8],2)
        else:
            input_df.iloc[index,21]=input_df.iloc[index,12]
    return input_df
def calculateQuantityDifference(input_df):    
    qdiff=[41,42,43,44,45,46,47,49,50,51,52,54,55,56,59.60,61,62,63,64,65,66]
    for index,row in civil_works_cost_df.iterrows():
        if index in qdiff:
            input_df.iloc[index,13]=input_df.iloc[index,8]-input_df.iloc[index,2]
        else:
            input_df.iloc[index,13]=0
    return input_df
        
    

def calculateUnitCostForCivilworks(civil_works_cost_df):
    for index,row in civil_works_cost_df.iterrows():
        if row[3]!="LS":
            civil_works_cost_df.iloc[index,9]=civil_works_cost_df.iloc[index,8]/civil_works_cost_df.iloc[index,4]
        else:
            civil_works_cost_df.iloc[index,4]=1
            civil_works_cost_df.iloc[index,9]= civil_works_cost_df.iloc[index,8]
    return civil_works_cost_df
def calccualteCostDistribution(cost_distribution_df,sec_8_df):
    codelist=list(cost_distribution_df['costcode'])
    n=cost_distribution_df.shape[0]
    myvalue=[0 for i in range(0,n)]
    cost_distribution_df.iloc[:,3]=myvalue
    cost_distribution_df.iloc[:,3]=myvalue
    
    for index,row in sec_8_df.iterrows():
        code=row[23]
        myrow=codelist.index(code)
        cost_distribution_df.iloc[myrow,3]=cost_distribution_df.iloc[myrow,3]+row[6]
        cost_distribution_df.iloc[myrow,4]=cost_distribution_df.iloc[myrow,4]+row[12]
    cost_distribution_df.iloc[:,5]= cost_distribution_df.iloc[:,4]-cost_distribution_df.iloc[:,3]
    return cost_distribution_df
        
def calculateWeight(input_df):
    value=sum(list(input_df["TotalCost"]))
    input_df['Weight']=input_df["TotalCost"]/value
    mylist=list(input_df['Weight'])
    mylist=[round(x,5) for x in mylist]
    correction=sum(mylist)-1.00000    
    input_df['Weight']=mylist
    input_df.iloc[63,6]=input_df.iloc[63,6]-correction
    return input_df

In [3]:
"""Functions Related to Tranfering Data to Excel Sheet"""
def writeDataframe6(wbpath,df,sheetname,dfcols,xlcols,indexcol):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]    
    for index,row in df.iterrows():        
        myrow=int(row[indexcol])
        for idf,ixl in zip(dfcols,xlcols):
            wsheet.cell(row=myrow,column=ixl).value=row[idf]               
    wb.save(wbpath)
def saveDataFrame(dataframes,filepath,names):
    writer = pd.ExcelWriter(filepath, engine='xlsxwriter')
    for df,sname in zip(dataframes,names):
        df.to_excel(writer,sheet_name=sname)   
    writer.save()  
def writeDataframe7(wbpath,df,sheetname,dfcols,xlcols,indexcol):     
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]    
    for index,row in df.iterrows():        
        myrow=int(row[indexcol])
        for idf,ixl in zip(dfcols,xlcols):
            if row[idf]==0:
                wsheet.cell(row=myrow,column=ixl).value="" 
            elif row[idf]=="":
                 wsheet.cell(row=myrow,column=ixl).value=""
            else:
                wsheet.cell(row=myrow,column=ixl).value=row[idf]                    
    wb.save(wbpath)
def writeDataframe8(wbpath,df,sheetname,dfcols,xlcols,rowlist):    
    wb=opxl.load_workbook(wbpath)
    wsheet=wb[sheetname]    
    for index,row in df.iterrows():        
        myrow=rowlist[index]
        print(myrow)
        for idf,ixl in zip(dfcols,xlcols):
            if row[idf]==0:
                wsheet.cell(row=myrow,column=ixl).value="" 
            elif row[idf]=="":
                 wsheet.cell(row=myrow,column=ixl).value=""
            else:
                wsheet.cell(row=myrow,column=ixl).value=row[idf]                    
    wb.save(wbpath)
def calcualteEconomicCost(fcost_df):
    fcost_df["2014-15"]=fcost_df["2014-15"]*fcost_df["EC_FACTOR"]
    fcost_df["2015-16"]=fcost_df["2015-16"]*fcost_df["EC_FACTOR"]
    fcost_df["2016-17"]=fcost_df["2016-17"]*fcost_df["EC_FACTOR"]
    fcost_df["2017-18"]=fcost_df["2017-18"]*fcost_df["EC_FACTOR"]
    fcost_df["2018-19"]=fcost_df["2018-19"]*fcost_df["EC_FACTOR"]
    fcost_df["2019-20"]=fcost_df["2019-20"]*fcost_df["EC_FACTOR"]
    fcost_df["2020-21"]=fcost_df["2020-21"]*fcost_df["EC_FACTOR"]
    fcost_df["2021-22"]=fcost_df["2021-22"]*fcost_df["EC_FACTOR"]
    return  fcost_df
def assembleFIRR_EIRR_DF(fcost_df,ecost_df,FIRR_EIRR_Input):
    FIRR_EIRR_Input.iloc[0,1]=sum(list(fcost_df["2014-15"]))
    FIRR_EIRR_Input.iloc[0,2]=sum(list(ecost_df["2014-15"]))
    FIRR_EIRR_Input.iloc[1,1]=sum(list(fcost_df["2015-16"]))
    FIRR_EIRR_Input.iloc[1,2]=sum(list(ecost_df["2015-16"]))
    FIRR_EIRR_Input.iloc[2,1]=sum(list(fcost_df["2016-17"]))
    FIRR_EIRR_Input.iloc[2,2]=sum(list(ecost_df["2016-17"]))
    FIRR_EIRR_Input.iloc[3,1]=sum(list(fcost_df["2017-18"]))
    FIRR_EIRR_Input.iloc[3,2]=sum(list(ecost_df["2017-18"]))
    FIRR_EIRR_Input.iloc[4,1]=sum(list(fcost_df["2018-19"]))
    FIRR_EIRR_Input.iloc[4,2]=sum(list(ecost_df["2018-19"]))
    FIRR_EIRR_Input.iloc[5,1]=sum(list(fcost_df["2019-20"]))
    FIRR_EIRR_Input.iloc[5,2]=sum(list(ecost_df["2019-20"]))
    FIRR_EIRR_Input.iloc[6,1]=sum(list(fcost_df["2020-21"]))
    FIRR_EIRR_Input.iloc[6,2]=sum(list(ecost_df["2020-21"]))
    FIRR_EIRR_Input.iloc[7,1]=sum(list(fcost_df["2021-22"]))
    FIRR_EIRR_Input.iloc[7,2]=sum(list(ecost_df["2021-22"]))
    return FIRR_EIRR_Input

In [4]:
"This cell contains Annexure Data Processing Related Fucntions"
def assembeAnnex2DF(annex2_input_df):
    trmc=[]
    foreigntraining=[18]
    deadcodes=[43,44,45,46,47,49,50,51,52]
    for index,row in annex2_input_df.iterrows():
        if index not in deadcodes:
            tc=0
            for i in range(7,13):
                tc +=annex2_input_df.iloc[index,i]
            remaining=annex2_input_df.iloc[index,5]-tc
            if remaining <0:
                annex2_input_df.iloc[index,13]=0
                annex2_input_df.iloc[index,14]=0
                annex2_input_df.iloc[index,12]=annex2_input_df.iloc[index,12]+remaining
            else:
                minval=0.55
                maxval=0.63
                value=random()
                multiplier=minval+value*(maxval-minval)
                annex2_input_df.iloc[index,13]=round(remaining*multiplier,2)
                annex2_input_df.iloc[index,14]=round(remaining*(1-multiplier),2)
                if index in foreigntraining:
                    annex2_input_df.iloc[index,13]=0
                    annex2_input_df.iloc[index,14]= remaining
        else:
            annex2_input_df.iloc[index,13]=0
            annex2_input_df.iloc[index,14]=0
            
    return annex2_input_df

def assembeAnnex2DF2(annex2_input_df):
    annex2_input_df["Total_upto_19_20"]=annex2_input_df["2014-15"]+annex2_input_df["2015-16"]\
    +annex2_input_df["2016-17"]+annex2_input_df["2017-18"]+annex2_input_df["2018-19"]\
    +annex2_input_df["2019-20"]
    annex2_input_df["Remaining"]= annex2_input_df["TotalCost"]-annex2_input_df["Total_upto_19_20"]
    annex2_input_df["2020-21"]=annex2_input_df["Remaining"]*annex2_input_df["2020-21-P"]
    annex2_input_df["2021-22"]=annex2_input_df["Remaining"]*annex2_input_df["2021-22-P"]
    return annex2_input_df

def assembeAnnex9DF2(annex9_detail_df,annex2_input_df):
    data_19_20=list(annex2_input_df['2019-20'])
    data_20_21=list(annex2_input_df['2020-21'])
    data_21_22=list(annex2_input_df['2021-22'])
    annex9_detail_df['Total-19-20']=data_19_20
    annex9_detail_df['Total-20-21']=data_20_21
    annex9_detail_df['Total-21-22']=data_21_22
    civilworks=[56,57,58,59,60,61,62,63,64,65,66,67]
    ftrow=[18]    
    ltrow=[19,20,21]
    dparow=[24]
    gaterepair=[38]
    for index,row in annex9_detail_df.iterrows():        
        if index in ftrow:
            annex9_detail_df.iloc[index,8]=0
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=0
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]
            annex9_detail_df.iloc[index,14]=0
            annex9_detail_df.iloc[index,16]=0
            annex9_detail_df.iloc[index,17]=annex9_detail_df.iloc[index,15]
            annex9_detail_df.iloc[index,18]=0
        elif index in dparow:
            annex9_detail_df.iloc[index,8]=0
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,12]=0
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]
            annex9_detail_df.iloc[index,16]=0
            annex9_detail_df.iloc[index,17]=0
            annex9_detail_df.iloc[index,18]=annex9_detail_df.iloc[index,15]
        elif index in ltrow:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1072
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8928
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1072
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8928
            annex9_detail_df.iloc[index,14]=0
            annex9_detail_df.iloc[index,16]=annex9_detail_df.iloc[index,15]*0.1072
            annex9_detail_df.iloc[index,17]=annex9_detail_df.iloc[index,15]*0.8928
            annex9_detail_df.iloc[index,18]=0

        elif index in gaterepair:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1472
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8528
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1472
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8528
            annex9_detail_df.iloc[index,14]=0
            annex9_detail_df.iloc[index,16]=annex9_detail_df.iloc[index,15]*0.1472
            annex9_detail_df.iloc[index,17]=annex9_detail_df.iloc[index,15]*0.8528
            annex9_detail_df.iloc[index,18]=0
        elif index in civilworks:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1400
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8600
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1400
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8600
            annex9_detail_df.iloc[index,14]=0
            annex9_detail_df.iloc[index,16]=annex9_detail_df.iloc[index,15]*0.1400
            annex9_detail_df.iloc[index,17]=annex9_detail_df.iloc[index,15]*0.8600
            annex9_detail_df.iloc[index,18]=0
        else:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=0
            annex9_detail_df.iloc[index,16]=annex9_detail_df.iloc[index,15]
            annex9_detail_df.iloc[index,17]=0
            annex9_detail_df.iloc[index,18]=0        
    return annex9_detail_df
def checkAnnex9DF(annex9_detail_df,annex2_input_df):
    totalcost=list(annex2_input_df['TotalCost'])
    annex9_detail_df['Total-DPP-Cost']=totalcost
    annex9_detail_df['Total-Phased-Cost-1']=annex9_detail_df['Total-cum']+annex9_detail_df['Total-19-20']+annex9_detail_df['Total-20-21']+annex9_detail_df['Total-21-22']
    #annex9_detail_df['Total-Phased-Cost-2']=annex9_detail_df['GoB-cum']+annex9_detail_df['GoB-19-20']+annex9_detail_df['GoB-20-21']+annex9_detail_df['GoB-21-22']\
    #+annex9_detail_df['RPA-cum']+annex9_detail_df['RPA-19-20']+annex9_detail_df['RPA-20-21']+annex9_detail_df['RPA-21-22']\
    #+annex9_detail_df['DPA-cum']+annex9_detail_df['DPA-19-20']+annex9_detail_df['DPA-20-21']+annex9_detail_df['DPA-21-22']
    annex9_detail_df['Total-Phased-GoB']=annex9_detail_df['GoB-cum']+annex9_detail_df['GoB-19-20']+annex9_detail_df['GoB-20-21']+annex9_detail_df['GoB-21-22']
    annex9_detail_df['Total-Phased-RPA']=annex9_detail_df['RPA-cum']+annex9_detail_df['RPA-19-20']+annex9_detail_df['RPA-20-21']+annex9_detail_df['RPA-21-22']
    annex9_detail_df['Total-Phased-DPA']=annex9_detail_df['DPA-cum']+annex9_detail_df['DPA-19-20']+annex9_detail_df['DPA-20-21']+annex9_detail_df['DPA-21-22']
    annex9_detail_df['Total-Phased-Cost-2']= annex9_detail_df['Total-Phased-GoB']+annex9_detail_df['Total-Phased-RPA']+annex9_detail_df['Total-Phased-DPA']
    annex9_detail_df['Check1']=annex9_detail_df['Total-DPP-Cost']-annex9_detail_df['Total-Phased-Cost-1']
    annex9_detail_df['Check2']=annex9_detail_df['Total-DPP-Cost']-annex9_detail_df['Total-Phased-Cost-2']
    annex9_detail_df.round({'Check1':2})
    return annex9_detail_df
def findDifferenceForSec8(mydf):
    #GOB_1st	RPA_1st	DPA_1st	TOTAL_1st	rindex	Quantity_2nd	GOB_2nd	RPA_2nd	DPA_2nd	TOTAL_2nd	Quantity_diff	GOB_Diff	RPA_diff	DPA_diff	TOTAL_diff
    """Difference"""
    mydf['TOTAL_diff']=mydf['TOTAL_2nd']-mydf['TOTAL_1st']
    mydf['GOB_diff']=mydf['GOB_2nd']-mydf['GOB_1st']
    mydf['RPA_diff']=mydf['RPA_2nd']-mydf['RPA_1st']
    mydf['DPA_diff']=mydf['DPA_2nd']-mydf['DPA_1st']
    """Total 1st Revised"""
    mydf['TOTAL_1st']=mydf['GOB_1st']+mydf['RPA_1st']+mydf['DPA_1st']    
    return mydf

In [5]:
"""New Section9 Detail Phasing"""
def changeCumulativeDF(input_df):
    for index,row in input_df.iterrows():
        input_df.iloc[index,3]=input_df.iloc[index,3]+row['Total-19-20']
        input_df.iloc[index,4]=input_df.iloc[index,4]+row['GoB-19-20']
        input_df.iloc[index,5]=input_df.iloc[index,5]+row['RPA-19-20']
        input_df.iloc[index,6]=input_df.iloc[index,6]+row['DPA-19-20']
    return input_df

def assembeAnnex9DF3(annex9_detail_df,annex2_input_df):
    data_19_20=list(annex2_input_df['2019-20'])
    data_20_21=list(annex2_input_df['2020-21'])
    data_21_22=list(annex2_input_df['2021-22'])    
    annex9_detail_df['Total-20-21']=data_20_21
    annex9_detail_df['Total-21-22']=data_21_22
    civilworks=[56,57,58,59,60,61,62,64,65,66,67]
    ftrow=[18]    
    ltrow=[19,20,21]
    dparow=[24]
    gaterepair=[38]
    embrow=[63]
    for index,row in annex9_detail_df.iterrows():        
        if index in ftrow:
            annex9_detail_df.iloc[index,8]=0
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=0
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=0
            
        elif index in dparow:
            annex9_detail_df.iloc[index,8]=0
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,12]=0
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]            
        elif index in ltrow:         
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1072
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8928
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1072
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8928
            annex9_detail_df.iloc[index,14]=0
        elif index in gaterepair:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1472
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8528
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1472
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8528
            annex9_detail_df.iloc[index,14]=0            
        elif index in civilworks:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.1400
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.8600
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.1400
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.8600
            annex9_detail_df.iloc[index,14]=0
        elif index in embrow:
            df_gob=0.6592
            df_rpa=0.3408
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*0.6592
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*0.3408
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*0.6592
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*0.3408
            annex9_detail_df.iloc[index,14]=0
            
        else:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=0                  
    return annex9_detail_df
def checkAnnex9DF(annex9_detail_df,annex2_input_df):
    totalcost=list(annex2_input_df['TotalCost'])
    annex9_detail_df['Total-DPP-Cost']=totalcost
    annex9_detail_df['Total-Phased-Cost-1']=annex9_detail_df['Total-cum']+annex9_detail_df['Total-20-21']+annex9_detail_df['Total-21-22']
    #annex9_detail_df['Total-Phased-Cost-2']=annex9_detail_df['GoB-cum']+annex9_detail_df['GoB-19-20']+annex9_detail_df['GoB-20-21']+annex9_detail_df['GoB-21-22']\
    #+annex9_detail_df['RPA-cum']+annex9_detail_df['RPA-19-20']+annex9_detail_df['RPA-20-21']+annex9_detail_df['RPA-21-22']\
    #+annex9_detail_df['DPA-cum']+annex9_detail_df['DPA-19-20']+annex9_detail_df['DPA-20-21']+annex9_detail_df['DPA-21-22']
    annex9_detail_df['Total-Phased-GoB']=annex9_detail_df['GoB-cum']+annex9_detail_df['GoB-20-21']+annex9_detail_df['GoB-21-22']
    annex9_detail_df['Total-Phased-RPA']=annex9_detail_df['RPA-cum']+annex9_detail_df['RPA-20-21']+annex9_detail_df['RPA-21-22']
    annex9_detail_df['Total-Phased-DPA']=annex9_detail_df['DPA-cum']+annex9_detail_df['DPA-20-21']+annex9_detail_df['DPA-21-22']
    annex9_detail_df['Total-Phased-Cost-2']= annex9_detail_df['Total-Phased-GoB']+annex9_detail_df['Total-Phased-RPA']+annex9_detail_df['Total-Phased-DPA']
    annex9_detail_df['Check1']=annex9_detail_df['Total-DPP-Cost']-annex9_detail_df['Total-Phased-Cost-1']
    annex9_detail_df['Check2']=annex9_detail_df['Total-DPP-Cost']-annex9_detail_df['Total-Phased-Cost-2']
    annex9_detail_df.round({'Check1':2})
    return annex9_detail_df
"""New Section9 Detail Phasing"""
def addTotalCost2Annex3(annex9_detail_df,sec8_df):
    'GOB_2nd RPA_2nd DPA_2nd TOTAL_2nd'
    allocation_gob=list(sec8_df['GOB_2nd'])
    allocation_rpa=list(sec8_df['RPA_2nd'])
    allocation_dpa=list(sec8_df['DPA_2nd'])
    allocation_total=list(sec8_df['TOTAL_2nd'])
    annex9_detail_df=annex9_detail_df.assign(Alloc_Total=allocation_total)
    annex9_detail_df=annex9_detail_df.assign(Alloc_GoB=allocation_gob)
    annex9_detail_df=annex9_detail_df.assign(Alloc_RPA=allocation_rpa)
    annex9_detail_df=annex9_detail_df.assign(Alloc_DPA=allocation_dpa)
    annex9_detail_df['Remaining_Total']= annex9_detail_df['Alloc_Total']- annex9_detail_df['Total-cum']
    annex9_detail_df['Remaining_Gob']= annex9_detail_df['Alloc_GoB']- annex9_detail_df['GoB-cum']
    annex9_detail_df['Remaining_RPA']= annex9_detail_df['Alloc_RPA']- annex9_detail_df['RPA-cum']
    annex9_detail_df['Remaining_DPA']= annex9_detail_df['Alloc_DPA']- annex9_detail_df['DPA-cum']
    return annex9_detail_df
"""New Section9 Detail Phasing"""

def getDistributionFactor(annex9_detail_df,index):
    rm_total=annex9_detail_df.iloc[index,19]
    rm_gob=annex9_detail_df.iloc[index,20]
    rm_rpa=annex9_detail_df.iloc[index,21]
    rm_dpa=annex9_detail_df.iloc[index,22]
    df_gob=round(rm_gob/rm_total,4)
    df_rpa=round(rm_rpa/rm_total,4)
    df_dpa=round(rm_dpa/rm_total,4)
    myvalue={'df_gob':df_gob,'df_rpa':df_rpa,'df_dpa':df_dpa}
    return myvalue
    



def assembeAnnex9DF4(annex9_detail_df,annex2_input_df):
    data_19_20=list(annex2_input_df['2019-20'])
    data_20_21=list(annex2_input_df['2020-21'])
    data_21_22=list(annex2_input_df['2021-22'])    
    annex9_detail_df['Total-20-21']=data_20_21
    annex9_detail_df['Total-21-22']=data_21_22
    civilworks=[56,57,58,59,60,61,62,64,65,66,67]
    ftrow=[18]    
    ltrow=[19,20,21]
    dparow=[24]
    gaterepair=[38]
    embrow=[63]
    for index,row in annex9_detail_df.iterrows():        
        if index in ftrow:
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']
            
        elif index in dparow:
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']                       
        elif index in ltrow:         
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']
            
        elif index in gaterepair:
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']            
          
        elif index in civilworks:
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']
            
        elif index in embrow:
            myvalue=getDistributionFactor(annex9_detail_df,index)            
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]*myvalue['df_gob']
            annex9_detail_df.iloc[index,9]=annex9_detail_df.iloc[index,7]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,10]=annex9_detail_df.iloc[index,7]*myvalue['df_dpa']
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]*myvalue['df_gob']
            annex9_detail_df.iloc[index,13]=annex9_detail_df.iloc[index,11]*myvalue['df_rpa']
            annex9_detail_df.iloc[index,14]=annex9_detail_df.iloc[index,11]*myvalue['df_dpa']                        
        else:
            annex9_detail_df.iloc[index,8]=annex9_detail_df.iloc[index,7]
            annex9_detail_df.iloc[index,9]=0
            annex9_detail_df.iloc[index,10]=0
            annex9_detail_df.iloc[index,12]=annex9_detail_df.iloc[index,11]
            annex9_detail_df.iloc[index,13]=0
            annex9_detail_df.iloc[index,14]=0                  
    return annex9_detail_df

In [6]:
"""This Part comapares Original and New DPP procurement Plan"""
def identifyEarthVolumeChangeRequirements(comparision_df):
    earth_work=[7,8,9,10,11]
    for index,row in comparision_df.iterrows():
        stccode=row['Structure_Code_New']
        if  stccode in earth_work:
            if row['Change_of_Quantity']!=0 or row['Change_of_Cost']!=0:
                comparision_df.iloc[index,14]="Yes"
    return comparision_df
            
        
        
    
def prepare_comparision_matrix(comparision_df):    
    for index,row in comparision_df.iterrows():
        print(index)
        if row['Structure_Code_Old'] !=row['Structure_Code_New']:
            comparision_df.iloc[index,9]="Yes"
        comparision_df.iloc[index,11]=comparision_df.iloc[index,7]-comparision_df.iloc[index,2]
        comparision_df.iloc[index,12]=comparision_df.iloc[index,8]-comparision_df.iloc[index,3]   
    return comparision_df

In [7]:
"""Haor Wise and Packawise Cost and Quantity Calcualtion.This part takes packagewise main 
data sheet and process data.Calcualtes Haorwise and Package wise cost and quantity.
Than Transfer Data to Input sheet Economic Code Wise Comparision Section 8"""
"Initialization code"
haorwise_cost_df=None
haorwise_quantity_df=None
input_df=None
#mypath=r'F:\Office Work\DPP_Revision\Civil_works'
"""Folder for Office Computer"""
mypath=r'F:\Office Work\IMED\DPP_Revised'
myfolder=r'F:\Office Work\IMED\DPP_Revised'
"""Folder for Home Computer"""
#mypath=r'E:\Website_26_07_2020\cmis6\IMED\DPP_Revised'
#myfolder=r'E:\Website_26_07_2020\cmis6\IMED\DPP_Revised'
cost_input_file_path=os.path.join(myfolder,'Revised_package_cost3.xlsx')
data_input_path=os.path.join(myfolder,'First_revised2.xlsx')
#mypath3=os.path.join(myfolder,'First_revised.xlsx')
sheetName="Revised"
input_df=pd.read_excel(cost_input_file_path,sheet_name=sheetName,index_col=None,header=0)
input_df.fillna(0,inplace=True)
#summarizing data haorwise
sheetName="Haor_wise_proforma"
output_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
output_df.fillna(0,inplace=True)
haorwise_quantity_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=30)
haorwise_quantity_df.fillna(0,inplace=True)
haorwise_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=30)
haorwise_cost_df.fillna(0,inplace=True)
sheetName="HaorCode"
haorCode_df=pd.read_excel(cost_input_file_path,sheet_name=sheetName,index_col=None,header=0)
output_df.fillna(0,inplace=True)
haor_list=list(haorCode_df["Code"])
haor_list
haorwise_quantity_df=aggregateWorksHaorWise(input_df,haorwise_quantity_df,haor_list)
wbpath=data_input_path
sheetName="Haor_wise_quantity"
dfcols=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
xlcols=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
writeDataframe6(wbpath,haorwise_quantity_df,sheetName,dfcols,xlcols,20)
sheetName="Haor_wise_cost"
#haorwise_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=30)
haorwise_cost_df=aggregateCostHaorWise(input_df,haorwise_cost_df,haor_list)
dfcols=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
xlcols=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
writeDataframe6(wbpath,haorwise_cost_df,sheetName,dfcols,xlcols,20)

offset=2
#writeDataframe5(wbpath,output_df,sheetName,dfcols,xlcols,offset) 
#output_cost_df=aggregateCostHaorWise(input_df,output_cost_df,haor_list)
#writeDataframe3(wbpath,output_df,sheetName,dfcols,xlcols,offset)
#sheetName="Haorwise_Work_Cost_List"
#writeDataframe3(wbpath,output_cost_df,sheetName,dfcols,xlcols,offset)
#output_cost_df=initializeCostDFToZero(output_cost_df)
#output_df=initializeCostDFToZero(output_df)
#summarizing data packagewise
#output_df=aggregateWorksHaorWise(input_df,output_df,haor_list)
sheetName="Package_wise_proforma"
packagewise_quantity_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
packagewise_quantity_df.fillna(0,inplace=True)
package_list=list(packagewise_quantity_df['Name'])
packagewise_quantity_df=aggregateWorksPackageWise(input_df,packagewise_quantity_df,package_list)
sheetName="Package_wise_quantity"
writeDataframe3(wbpath,packagewise_quantity_df,sheetName,dfcols,xlcols,offset)
sheetName="Package_wise_proforma"
packagewise_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)#packagewise_cost_df.fillna(0,inplace=True)
packagewise_cost_df.fillna(0,inplace=True)
packagewise_cost_df=aggregateCostPackageWise(input_df,packagewise_cost_df,package_list)
sheetName="Package_wise_cost"
writeDataframe3(wbpath,packagewise_cost_df,sheetName,dfcols,xlcols,offset)

In [8]:
input_df

,Package Name,Component,Unit,Qnty,Cost,Remarks,Package,Haor Type,Structure Code,Earth Volume,Hoar Code,District Code
0,BWDB/Brah/HFMLIP/PW-01,Regulator Rehablitation,nos,2.000,87.50,0,BRAH/PW-01,New,16,0,R-14,BRAH
1,BWDB/Brah/HFMLIP/PW-01,Regulator Rehablitation,nos,2.000,87.50,0,BRAH/PW-01,New,16,0,R-15,BRAH
2,BWDB/Hobi/HFMLIP/PW-01\nBashira River,Rehablitation of Submersible Embankment,Km,0.000,0.00,0,HOBI/PW-01,0,1,0,R-8,HOBI
3,BWDB/Hobi/HFMLIP/PW-01\nBashira River,,nos.,1.000,27.05,Need rehabilitation of existing 3-vent regulat...,HOBI/PW-01,Rehab,2,,R-8,HOBI
4,BWDB/Hobi/HFMLIP/PW-02\nAralia Khal,Construction of Causeway for Aralia (4&6m).,nos.,1.000,300.00,Need 6.0 m causeway instead of 4.0 m causeway.,HOBI/PW-01,Rehab,2,0,R-8,HOBI
...,...,...,...,...,...,...,...,...,...,...,...,...
169,BWDB/Sunam/HFMLIP/PW-04\nDharmapasha Rui Bill ...,Const. of Submersible Embankment,nos.,3.000,722.00,0,SUNM/PW-05,New,5,0,N-12,SUNM
170,BWDB/Sunam/HFMLIP/PW-01\nDhakua Haor (Divn-2),Const. of Irrigation Inlet,nos.,12.000,131.28,0,SUNM/PW-06,New,1,0,N-12,SUNM
171,BWDB/Sunam/HFMLIP/PW-03\nDhakua Haor (Divn-1),Const. of New Regulators 2 vent (1.50mx1.80m),nos.,1.000,45.13,0,SUNM/PW-06,New,4,0,N-12,SUNM
172,BWDB/Sunam/HFMLIP/PW-05\nDharmapasha Rui Bill ...,Const. of 6.0 m width Causeway,Km,66.043,1423.59,0,SUNM/PW-06,New,7,0,N-12,SUNM
173,Construction of Submersible Embankment with Sl...,Re-excavation of Khal (New Haor),Km,3.545,1474.48,0,SUNM/PW-07,New,11,0,N-12,SUNM

In [9]:
"""Calculating and Transferring Civil works cost to revised cost input file"""
sheetName="Transfer_Civilwork"
civil_works_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
civil_works_cost_df.fillna(0,inplace=True) 
#civil_works_cost_df2=civil_works_cost_df
sheetName="Structure_To_Dpp_Item"
structurewise_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
structurewise_cost_df.fillna(0,inplace=True)
stcodes=list(structurewise_cost_df.iloc[:,1])
dppcodes=list(structurewise_cost_df.iloc[:,2])
structurewise_cost_df=aggrgateCostByStructureCode(input_df,structurewise_cost_df,stcodes)
civil_works_cost_df=transferStructureCostToDPPCost(structurewise_cost_df,civil_works_cost_df)

sheetName="revised_data"
wbpath=data_input_path
dfcols=[5,6,7,8]
xlcols=[3,4,5,6]
writeDataframe6(wbpath,civil_works_cost_df,sheetName,dfcols,xlcols,2)
sheetName="quantity"
dfcols=[4]
xlcols=[6]
writeDataframe6(wbpath,civil_works_cost_df,sheetName,dfcols,xlcols,2)

In [10]:
structurewise_cost_df

,name,stcode,Dpptransfer,Unit,Quantity,GoB,RPA,DPA,Total,Annex_input_Transfer,Dpp_Transfer_row
0,Construction of Irrigation Inlet,1,1,Nos,119.000,170.8644,1049.5956,0.0,1220.46,0.0,0.0
1,Rehab Regulator Rehab Haor,2,2,Nos,5.000,164.1668,1008.4532,0.0,1172.62,0.0,0.0
2,Regulator,3,3,Nos,40.000,1348.5584,8284.0016,0.0,9632.56,0.0,0.0
3,Box Drainage Outlet,4,3,Nos,43.000,271.1436,1665.5964,0.0,1936.74,0.0,0.0
4,Causeway,5,3,Nos,28.000,959.2898,5892.7802,0.0,6852.07,0.0,0.0
5,Bridge,6,3,Nos,0.000,0.0000,0.0000,0.0,0.00,0.0,0.0
6,Khal_River Reexcavation(New Haor),7,4,Km,336.214,1425.7782,8758.3518,0.0,10184.13,0.0,0.0
7,Khal_River Reexcavation(Rehab Haor),8,5,Km,108.974,475.8446,2923.0454,0.0,3398.89,0.0,0.0
8,Embankment Rehablitation,9,6,Km,67.110,284.9602,1750.4698,0.0,2035.43,0.0,0.0
9,Submersible Embankment Rehabilitation,10,7,Km,62.662,244.7802,1503.6498,0.0,1748.43,0.0,0.0
10,Submersible Embankment Construction,11,8,Km,261.238,3002.3322,18442.8978,0.0,21445.23,0.0,0.0
11,Rehab Regulator New Haor,12,9,Nos,7.000,20.5366,126.1534,0.0,146.69,0.0,0.0
12,Embankment Slope Protection Work,13,8,Km,0.000,0.0000,0.0000,0.0,0.00,0.0,0.0
13,Thrashing Floor Construction,14,10,Nos,5.000,31.5000,193.5000,0.0,225.00,0.0,0.0
14,Construction of WMG,15,11,Nos,55.000,226.5200,1391.4800,0.0,1618.00,0.0,0.0
15,Gate Repair By M&E,16,12,Nos,86.000,56.7770,348.7730,0.0,405.55,0.0,0.0
16,O&M During Construction,17,13,LS,1.000,120.0000,0.0000,0.0,120.00,0.0,0.0

In [11]:
civil_works_cost_df

,Code,Description,rindex,unit,Quantity,GOB,RPA,DPA,TOTAL,Unitcost,Tindex
0,4111306,Construction of Irrigation Inlet (New Haors),58,Nos,119.000,170.8644,1049.5956,0,1220.46,0,2
1,4111307,Re-installation/Construction of Regulator/ Ca...,59,Nos,5.000,164.1668,1008.4532,0,1172.62,0,3
2,4111307,Installation/Construction of New Regulators/ ...,60,Nos,111.000,2578.9918,15842.3782,0,18421.37,0,4
3,4111307,Re-excavation of Khal/River (New Haors),61,Km,336.214,1425.7782,8758.3518,0,10184.13,0,5
4,4111201,Re-excavation of Khal/River (Rehabilitation S...,62,Km,108.974,475.8446,2923.0454,0,3398.89,0,6
5,4111201,Rehabilitation of Full Embankment (Resection/...,63,Km,67.110,284.9602,1750.4698,0,2035.43,0,7
6,4111201,Rehabilitation of Submergible Embankment (Re...,64,Km,62.662,244.7802,1503.6498,0,1748.43,0,8
7,4111201,Construction of Submersible Embankment (New Ha...,65,Km,261.238,3002.3322,18442.8978,0,21445.23,0,9
8,4111201,Rehabilitation of Regulator (New Haors),66,Nos,7.000,20.5366,126.1534,0,146.69,0,10
9,4111201,Threshing Floor Construction,67,Nos,5.000,31.5000,193.5000,0,225.00,0,11
10,4111201,Construction of WMG Office,68,Nos,55.000,226.5200,1391.4800,0,1618.00,0,12
11,3258114,Gate Repair By M&E,40,Nos,86.000,56.7770,348.7730,0,405.55,0,13
12,4111201,O&M During Construction,69,LS,1.000,120.0000,0.0000,0,120.00,0,14

In [12]:
"""Transfering Data to Annex Preparation Sheet  """
wbpath=os.path.join(myfolder,"Annex_input.xlsx")
sheetName="Yearly_EXP"
#civil_works_cost_df['TOTAL']=civil_works_cost_df['GOB']+civil_works_cost_df['RPA']+civil_works_cost_df['DPA']
#civil_works_cost_df['Unitcost']=civil_works_cost_df['TOTAL']/civil_works_cost_df['Quantity']
civil_works_cost_df=calculateUnitCostForCivilworks(civil_works_cost_df)
dfcols=[9,8,4]
xlcols=[4,6,5]
writeDataframe6(wbpath,civil_works_cost_df,sheetName,dfcols,xlcols,2)
dfcols=[0,1,2,3,4,5,6,7,8,9]
xlcols=[1,2,3,4,5,6,7,8,9,10]
sheetName="Transfer_Civilwork"
rowlist=[2,3,4,5,6,7,8,9,10,11,12,13]
#writeDataframe8(data_input_path,civil_works_cost_df,sheetName,dfcols,xlcols,rowlist)
writeDataframe6(data_input_path,civil_works_cost_df,sheetName,dfcols,xlcols,10)
"""Creating District Wisre Summary"""
sheetName="District_Wise_Proforma"
districtwise_cost_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
districtwise_cost_df.fillna(0,inplace=True)
districtwise_quantity_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
districtwise_quantity_df.fillna(0,inplace=True)
#districtwise_quantity_df=
district_code=list(districtwise_cost_df["Sub-Project No"])
districtwise_quantity_df=aggregateWorksDistricWise(input_df,districtwise_quantity_df,district_code)
districtwise_cost_df=aggregateCostDistrictWise(input_df,districtwise_cost_df,district_code)
dfcols=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
xlcols=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
wbpath=data_input_path
sheetName="District_Wise_Quantity"
writeDataframe6(wbpath,districtwise_quantity_df,sheetName,dfcols,xlcols,20)
sheetName="District_Wise_Cost"
writeDataframe6(wbpath,districtwise_cost_df,sheetName,dfcols,xlcols,20)

In [13]:
districtwise_cost_df

,Name,Sub-Project No,Construction of Irrigation Inlet,Rehab Regulator Rehab Haor,Regulator,Box Drainage Outlet,Causeway,Bridge,Khal_River Reexcavation(New Haor),Khal_River Reexcavation(Rehab Haor),...,Submersible Embankment Rehabilitation,Submersible Embankment Construction,Rehab Regulator New Haor,Embankment Slope Protection,Thrashing Floor Construction,Construction of WMG,ME Gate Repair,O&M During Construction,Total,rrow_index
0,Kishoreganj,KISH,794.19,0.00,5743.73,666.98,3991.00,0.0,4590.03,496.55,...,0.00,16646.89,125.00,0.0,225.0,1618.0,55.55,120.0,35072.92,2
1,Hobiganj,HOBI,134.00,783.05,1091.95,540.00,1011.00,0.0,926.76,912.34,...,1365.43,1161.49,9.69,0.0,0.0,0.0,35.00,0.0,7970.71,3
2,Netrokona,NETR,53.92,389.57,1642.10,383.00,0.00,0.0,1365.00,1990.00,...,383.00,57.25,12.00,0.0,0.0,0.0,140.00,0.0,8451.27,4
3,Sunamgonj,SUNM,238.35,0.00,1154.78,346.76,1850.07,0.0,3302.34,0.00,...,0.00,3579.60,0.00,0.0,0.0,0.0,0.00,0.0,10471.90,5
4,Brahmanbaria,BRAH,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.00,0.00,0.00,0.0,0.0,0.0,175.00,0.0,175.00,6

In [14]:
"""Writing Section 8 and updating annexinput"""
sheetName="Sec8_proforma"
sec8_total_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=70)
sec8_total_df.fillna(0,inplace=True)
sheetName="quantity"
myquantity_df=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
myquantity_df.fillna(0,inplace=True)
sec8_total_df_corrected=addQuantity(sec8_total_df,myquantity_df)
sheetName="revised_data"
revised_dpp_cost=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0)
revised_dpp_cost.fillna(0,inplace=True)
sec8_total_df_corrected=addRevisedCost(revised_dpp_cost,sec8_total_df_corrected)
sec8_total_df_corrected=applyRPACorrections(sec8_total_df_corrected)
sec8_total_df_corrected=calculateDifference(sec8_total_df_corrected)
sec8_total_df_corrected=calcualteUnitCost(sec8_total_df_corrected)
sec8_total_df_corrected=calculateQuantityDifference(sec8_total_df_corrected)
dfcols=[2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,0,1]
xlcols=[3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,1,2]
sheetName="Sec8_Data"
sec8_total_df_corrected['units']=0
sec8_total_df_corrected['units']=myquantity_df['U1']
section_8_path=os.path.join(myfolder,"revised2.xlsx")
writeDataframe6(wbpath,sec8_total_df_corrected,sheetName,dfcols,xlcols,18)

In [15]:
sec8_total_df_corrected

,Code,Description,Quantity_1st,GOB_1st,RPA_1st,DPA_1st,TOTAL_1st,rindex,Quantity_2nd,GOB_2nd,...,GOB_Diff,RPA_diff,DPA_diff,TOTAL_diff,Tindex,annex2_input_index,annex9_input_index,UintCost,units,costcode
0,3111302.0,Conveyance Allowance,1 Item,10.00,0.00,0.0,10.00,12,1 Item,5.00,...,-5.00,0.00,0.0,-5.00,2,2,2,5.00,0,1
1,3111327.0,Overtime Allowance,1 Item,10.00,0.00,0.0,10.00,13,1 Item,10.00,...,0.00,0.00,0.0,0.00,3,3,3,10.00,0,1
2,3111338.0,Other Allowance,1 Item,140.00,0.00,0.0,140.00,14,1 Item,140.00,...,0.00,0.00,0.0,0.00,4,4,4,140.00,0,1
3,3241101.0,Travel Expenses (TA & DA for PMO & PIU),1 Item,100.00,0.00,0.0,100.00,16,1 Item,120.00,...,20.00,0.00,0.0,20.00,5,5,5,120.00,0,1
4,3211129.0,"Rent-Office : Office Accomodation for PMO (3,5...",1 Item,245.00,0.00,0.0,245.00,17,1 Item,245.00,...,0.00,0.00,0.0,0.00,6,6,6,245.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,4111201.0,Threshing Floor Construction,0,0.00,0.00,0.0,0.00,101,5,31.50,...,31.50,193.50,0.0,225.00,67,67,67,45.00,Nos,8
66,4111201.0,Construction of WMG Office,60,165.60,1214.40,0.0,1380.00,102,55,226.52,...,60.92,177.08,0.0,238.00,68,68,68,29.42,Nos,8
67,4111201.0,O&M During Construction,L.S,200.00,0.00,0.0,200.00,103,1,120.00,...,-80.00,0.00,0.0,-80.00,69,69,69,0.00,Iten,8
68,0.0,(c) Physical Contingency ( Lump sum):,L.S.,100.00,158.00,0.0,258.00,106,L.S.,30.51,...,-69.49,-158.00,0.0,-227.49,70,70,70,0.00,Item,9
69,0.0,(d) Price Contingency (Lump sum):,L.S.,100.76,301.38,0.0,402.14,107,L.S.,10.00,...,-90.76,-301.38,0.0,-392.14,71,71,71,0.00,Item,9

In [16]:
"""transfering data from Section8 to annexes"""
section_8_path=os.path.join(myfolder,"revised2.xlsx")
sheetName="Sec8_Data"
sec8_total_df_corrected=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=70)
sec8_total_df_corrected.fillna(0,inplace=True)
sec8_total_df_corrected=findDifferenceForSec8(sec8_total_df_corrected)
dfcols=[6,3,4,5,12,9,10,11,17,14,15,16,0,1]
xlcols=[6,7,9,10,15,16,18,19,24,25,27,28,2,3]
#dfcols=[6,3,4,5]
#xlcols=[6,7,9,10]
sheetName="Revised_2nd"
writeDataframe6(section_8_path,sec8_total_df_corrected,sheetName,dfcols,xlcols,7)
dfcols=[1,2,8,13,22,22,22]
xlcols=[3,5,14,23,4,13,22]
sheetName="Revised_2nd"
writeDataframe7(section_8_path,sec8_total_df_corrected,sheetName,dfcols,xlcols,7)
sec8_total_df_corrected=None
sheetName="Sec8_Data"
sec8_total_df_corrected=pd.read_excel(data_input_path,sheet_name=sheetName,index_col=None,header=0,nrows=70)
dfcols=[21,8,12,0,1]
xlcols=[4,5,6,1,2]
sheetName="Yearly_EXP"
writeDataframe7(data_input_path,sec8_total_df_corrected,sheetName,dfcols,xlcols,19)
sheetName="Detail_9_input"
dfcols=[0,1]
xlcols=[1,2]
writeDataframe7(data_input_path,sec8_total_df_corrected,sheetName,dfcols,xlcols,19)
"""###############Writing Annex-II ##########################
###########################################"""
annex2_input_sheetname="Yearly_EXP"
annex2_output_sheetname="Annex-II"
annex_input_path=data_input_path
annex_output_path=section_8_path
annex2_input_df=pd.read_excel(annex_input_path,sheet_name=annex2_input_sheetname,
                              index_col=None,header=0,nrows=70)
annex2_input_df.fillna(0,inplace=True)
annex2_input_df=assembeAnnex2DF2(annex2_input_df)
annex2_input_df=calculateWeight(annex2_input_df)
dfcols=[3,4,5,6,7,8,9,10,11,12,13,14,0,1]
xlcols=[5,6,7,8,9,12,15,18,21,24,27,30,2,3]
writeDataframe6(annex_output_path,annex2_input_df,annex2_output_sheetname,dfcols,xlcols,2)
sheetName="Inves._Cost"
dfcols=[5,7,8,9,10,11,12,13,14,0,1]
xlcols=[4,5,6,7,8,9,10,11,12,2,3]
writeDataframe6(annex_output_path,annex2_input_df,sheetName,dfcols,xlcols,17)
sheetName="Economic_Factor_Input"
economic_factor_df=pd.read_excel(annex_input_path,
                                 sheet_name=sheetName,index_col=None,header=0)
economic_factor_df.fillna(0,inplace=True)
myfactor=list(economic_factor_df["Economic_Factor"])
annex2_input_df["EC_FACTOR"]=myfactor
ecost_df=annex2_input_df.loc[:,["2014-15","2015-16","2016-17","2017-18",
                                "2018-19","2019-20","2020-21","2021-22","EC_FACTOR"]]
ecost_df=calcualteEconomicCost(ecost_df)
fcost_df=annex2_input_df.loc[:,["2014-15","2015-16","2016-17","2017-18",
                                "2018-19","2019-20","2020-21","2021-22","EC_FACTOR"]]
sheetName="FIRR_EIRR_Input"
FIRR_EIRR_Input_df=pd.read_excel(annex_input_path,sheet_name=sheetName,index_col=None,header=0)
FIRR_EIRR_Input_df.fillna(0,inplace=True) 
FIRR_EIRR_Input_df=assembleFIRR_EIRR_DF(fcost_df,ecost_df,FIRR_EIRR_Input_df)
dfcols=[1,2]
xlcols=[2,3]
row_list=[2,3,4,5,6,7,8,9]
writeDataframe8(data_input_path,FIRR_EIRR_Input_df,sheetName,dfcols,xlcols,row_list)                             
sheetName="FIRR"                            
dfcols=[1]
xlcols=[2]
writeDataframe6(annex_output_path,FIRR_EIRR_Input_df,sheetName,dfcols,xlcols,3)
sheetName="EIRR"                            
dfcols=[2]
xlcols=[2]
writeDataframe6(annex_output_path,FIRR_EIRR_Input_df,sheetName,dfcols,xlcols,3)
"""###############Writing Annex9######################
###############################################"""
annex9_output_sheetname="9.Detil Phasing"
annex9_input_sheetname="Detail_9_input"
annex9_detail_df=pd.read_excel(annex_input_path,
                               sheet_name=annex9_input_sheetname,index_col=None,header=0)
annex9_detail_df.fillna(0,inplace=True)
annex9_detail_df=assembeAnnex9DF2(annex9_detail_df,annex2_input_df)
annex9_detail_df=checkAnnex9DF(annex9_detail_df,annex2_input_df)
dfcols=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,0,1]
xlcols=[6,7,9,10,16,17,19,20,26,27,29,30,36,37,39,40,2,3]
writeDataframe6(annex_output_path,annex9_detail_df,annex9_output_sheetname,dfcols,xlcols,2) 
"""###############Writing Annex9######################
###############################################"""
annex9_input_sheetname="Detail_9_input2"
annex9_detail_df2=pd.read_excel(annex_input_path,
                               sheet_name=annex9_input_sheetname,index_col=None,header=0)
annex9_detail_df2.fillna(0,inplace=True)
annex9_detail_df2=addTotalCost2Annex3(annex9_detail_df2,sec8_total_df_corrected)
annex9_detail_df2=assembeAnnex9DF4(annex9_detail_df2,annex2_input_df)
annex9_detail_df2=checkAnnex9DF(annex9_detail_df2,annex2_input_df)
#annex9_detail_df2=annex9_detail_df.copy(deep=True)
#annex9_detail_df2= changeCumulativeDF(annex9_detail_df2)
annex9_output_sheetname="9.Detil Phasing_2"
#xlcols=[6,7,9,10,16,17,19,20,26,27,29,30,2,3]
#dfcols=[3,4,5,6,11,12,13,14,15,16,17,18,0,1]
xlcols=[6,7,9,10,16,17,19,20,26,27,29,30]
dfcols=[3,4,5,6,7,8,9,10,11,12,13,14]
writeDataframe6(annex_output_path,annex9_detail_df2,annex9_output_sheetname,dfcols,xlcols,2)

2
3
4
5
6
7
8
9

In [17]:
"""Preparing Summary of Changes Between Old and new DPP"""
sheetName="Comparision_proforma"
comparision_df=pd.read_excel(annex_input_path,sheet_name=sheetName,index_col=None,header=0)
comparision_df.fillna(0,inplace=True)
comparision_df=prepare_comparision_matrix(comparision_df)
comparision_df=identifyEarthVolumeChangeRequirements(comparision_df)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162

In [18]:
sheetName="distribution_of_cost"
cost_distribution_df=pd.read_excel(annex_input_path,sheet_name=sheetName,index_col=None,header=0)
cost_distribution_df.fillna(0,inplace=True)
cost_distribution_df['2nd revised']=0
cost_distribution_df['difference']=0
cost_distribution_df=calccualteCostDistribution(cost_distribution_df,sec8_total_df_corrected)
dfcols=[3,4,5]
xlcols=[4,5,6]
writeDataframe6(data_input_path,cost_distribution_df,sheetName,dfcols,xlcols,2)

In [19]:
"""#################Saving All Data Frames#################"""
dfpath=os.path.join(myfolder,"dframes.xlsx")
frames=[]
names=[]
frames.append(input_df)
names.append('Input_sheet')
frames.append(haorwise_quantity_df)
names.append('haor_wise_quantity')
frames.append(haorwise_cost_df)
names.append('haor_wise_cost')
frames.append(packagewise_quantity_df)
names.append("Package_wise_quantity")
frames.append(packagewise_cost_df)
names.append("Package_wise_cost")
frames.append(structurewise_cost_df)
names.append("Structure_wise_cost")
frames.append(civil_works_cost_df)
names.append("Civil_Works_Cost")
frames.append(districtwise_quantity_df)
names.append("district_wise_quantity")
frames.append(districtwise_cost_df)
names.append("district_wise_cost")
frames.append(sec8_total_df_corrected)
names.append("code_wise_costcomaprision")
frames.append(annex2_input_df)
names.append("Yearwise-cost-projection")
frames.append(annex9_detail_df)
names.append("Annex-9_detail_phasing")
frames.append(FIRR_EIRR_Input_df)
names.append("EIRR_INPUT")
frames.append(cost_distribution_df)
names.append("Distribution_of_cost")
frames.append(myquantity_df)
names.append("quantity_comaprision")
frames.append(annex9_detail_df2)
names.append("Annex-9_detail_phasing_modified")
frames.append(comparision_df)
names.append("Old_New_PP")
#sec8_total_df_corrected
#districtwise_cost_df
#districtwise_cost_df
saveDataFrame(frames,dfpath,names)

In [20]:
total=sum(list(sec8_total_df_corrected.iloc[:,6]))

In [21]:
total_weight=sum(list(annex2_input_df['Weight']))
total_weight

0.9999999999999999

In [22]:
total_weight

0.9999999999999999

In [23]:
cost_distribution_df

,Item,costcode,rindex,1st Revised,2nd revised,difference
0,Office Administration,1,2,5403.27,5638.35,235.08
1,Fuel & Lubricant,2,3,350.00,210.00,-140.00
2,Training and Livelihood,3,4,4491.97,5117.00,625.03
3,Consulatantcy,4,5,7901.40,7901.40,0.00
4,Repair & Maintenance,5,6,265.00,290.00,25.00
5,Vehicle & Equipments,6,7,1066.22,1054.22,-12.00
6,Land Acquisition,7,8,24000.00,18386.72,-5613.28
7,Civilworks,8,9,53727.00,62141.80,8414.80
8,contingency,9,10,660.14,40.51,-619.63

In [24]:
 print(annex_input_path)

F:\Office Work\IMED\DPP_Revised\First_revised2.xlsx

In [25]:
annex2_input_df

,Code,Description,rindex,Unit Cost,Quantity,TotalCost,Weight,2014-15,2015-16,2016-17,...,2018-19,2019-20,2020-21,2021-22,2020-21-P,2021-22-P,Investment_Cost_Index,Total_upto_19_20,Remaining,EC_FACTOR
0,3111302.0,Conveyance Allowance,10,5.00,1 Item,5.00,0.00005,0.00,0.30,0.13,...,0.30,0.50,2.0242,1.4658,0.58,0.42,9,1.51,3.49,0.902
1,3111327.0,Overtime Allowance,11,10.00,1 Item,10.00,0.00010,0.00,0.00,0.00,...,0.00,0.00,6.3000,3.7000,0.63,0.37,10,0.00,10.00,0.902
2,3111338.0,Other Allowance,12,140.00,1 Item,140.00,0.00139,0.00,0.00,0.00,...,11.61,14.00,53.6340,35.7560,0.60,0.40,11,50.61,89.39,0.902
3,3241101.0,Travel Expenses (TA & DA for PMO & PIU),14,120.00,1 Item,120.00,0.00119,0.99,11.92,14.98,...,12.70,14.97,28.8176,17.6624,0.62,0.38,13,73.52,46.48,0.902
4,3211129.0,"Rent-Office : Office Accomodation for PMO (3,5...",15,245.00,1 Item,245.00,0.00243,0.00,16.25,31.35,...,34.21,34.21,58.3544,35.7656,0.62,0.38,14,150.88,94.12,0.812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,4111201.0,Threshing Floor Construction,92,45.00,5,225.00,0.00223,0.00,0.00,0.00,...,0.00,0.00,123.7500,101.2500,0.55,0.45,91,0.00,225.00,2.761
66,4111201.0,Construction of WMG Office,93,29.42,55,1618.00,0.01605,0.00,0.00,0.00,...,42.09,93.33,845.0706,637.5094,0.57,0.43,92,135.42,1482.58,0.765
67,4111201.0,O&M During Construction,94,0.00,1,120.00,0.00119,0.00,0.00,0.00,...,0.00,0.00,66.0000,54.0000,0.55,0.45,93,0.00,120.00,0.761
68,0.0,(c) Physical Contingency ( Lump sum):,97,0.00,L.S.,30.51,0.00030,0.00,0.00,0.00,...,0.00,0.00,16.1703,14.3397,0.53,0.47,96,0.00,30.51,0.765
69,0.0,(d) Price Contingency (Lump sum):,98,0.00,L.S.,10.00,0.00010,0.00,0.00,0.00,...,0.00,0.00,5.4000,4.6000,0.54,0.46,97,0.00,10.00,0.000

In [26]:
districtwise_quantity_df

,Name,Sub-Project No,Construction of Irrigation Inlet,Rehab Regulator Rehab Haor,Regulator,Box Drainage Outlet,Causeway,Bridge,Khal_River Reexcavation(New Haor),Khal_River Reexcavation(Rehab Haor),...,Submersible Embankment Rehabilitation,Submersible Embankment Construction,Rehab Regulator New Haor,Embankment Slope Protection,Thrashing Floor Construction,Construction of WMG,ME Gate Repair,O&M During Construction,Total,rrow_index
0,Kishoreganj,KISH,78.0,0.0,24.0,19.0,15.0,0.0,158.165,11.551,...,0.000,179.327,5.0,0.0,5.0,55.0,13.0,1.0,0.0,2
1,Hobiganj,HOBI,15.0,4.0,6.0,9.0,5.0,0.0,30.058,23.007,...,49.352,23.815,1.0,0.0,0.0,0.0,13.0,0.0,0.0,3
2,Netrokona,NETR,5.0,1.0,6.0,7.0,0.0,0.0,31.440,74.416,...,13.310,3.071,1.0,0.0,0.0,0.0,56.0,0.0,0.0,4
3,Sunamgonj,SUNM,21.0,0.0,4.0,8.0,8.0,0.0,116.551,0.000,...,0.000,55.025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
4,Brahmanbaria,BRAH,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,...,0.000,0.000,0.0,0.0,0.0,0.0,4.0,0.0,0.0,6

In [27]:
comparision_df

,Name,unit,Quantity_Old,Cost_Old,PackageNo,Structure_Code_Old,Structure_Code_New,Quantity_New,Cost_New,Structure_Change,Change Details,Change_of_Quantity,Change_of_Cost,Poblems,Earth Volume Required,rindex
0,R-sectioning of Full Embankment,Km,5.000,10.0,KISH/PW-01,9,9,0.000,0.00,0,0.0,-5.000,-10.00,0.0,Yes,2
1,Replacement of Reg. Gates & other related works,nos.,13.000,32.5,KISH/PW-01,16,16,13.000,55.55,0,0.0,0.000,23.05,0.0,0,3
2,Re-excavation of Khal (Rehab.),Km,25.000,255.0,KISH/PW-01,8,8,11.551,496.55,0,0.0,-13.449,241.55,0.0,Yes,4
3,Cons. of Submersible Embankment,km,0.315,15.0,KISH/PW-02,11,11,0.315,15.59,0,0.0,0.000,0.59,0.0,Yes,5
4,Construction of New Regulators \n2 vent (1.50m...,nos.,1.000,145.0,KISH/PW-02,3,3,1.000,124.01,0,0.0,0.000,-20.99,0.0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,Cons. of 4.0 m width Causeway,nos.,6.000,330.0,SUNM/PW-08,5,5,0.000,0.00,0,0.0,-6.000,-330.00,0.0,0,160
159,Cons. of 6.0 m width Causeway,nos.,1.000,100.0,SUNM/PW-08,0,0,0.000,0.00,0,0.0,-1.000,-100.00,0.0,0,161
160,Cons. of Irrigation Inlet,nos.,4.000,40.0,SUNM/PW-08,1,1,0.000,0.00,0,0.0,-4.000,-40.00,0.0,0,162
161,Re-excavation of Khal (New Haor) \n,Km,6.100,90.0,SUNM/PW-08,7,7,0.000,0.00,0,0.0,-6.100,-90.00,0.0,Yes,163
162,Rehab/Replacement of Regulator Gates & other r...,nos.,4.000,100.0,BRAH/PW-01,16,16,4.000,175.00,0,0.0,0.000,75.00,0.0,0,164