In [65]:
import pandas as pd
from tkinter import *
from tkinter import filedialog
from tkinter.font import Font
import os
#import for writing Imed Report in Excel Sheet
import openpyxl as opxl

In [66]:
mypath=r'G:\IMED\Imed_calculation'
base_file=os.path.join(mypath,"Imed_funding.xlsx")
template_file_monthly=os.path.join(mypath,"IMED 05_BLANK.xlsx")
#df=pd.read_excel(base_file,sheet_name='DPP_ALLOCATION')
dpp_alloc=pd.read_excel(base_file,sheet_name='DPP_ALLOC',index_col=None,header=0)
dpp_alloc.fillna(0,inplace=True)
#dpp_alloc
imed_head=pd.read_excel(base_file,sheet_name="IMED_HEAD",index_col=None,header=0)
#imed_head
dpp_to_imed=pd.read_excel(base_file,sheet_name="DPP_TO_IMED",index_col=None,header=0)

In [67]:
cw=dpp_alloc[dpp_alloc['Imed']=='CAP_8']
cw

,Code,Description,GOB,RPA,DPA,TOTAL,Imed,Imed_Code,Physical
56,4111306.0,Construction of Irrigation Inlet (New Haors),151.32,1109.68,0.0,1261.0,CAP_8,CAP_8,1.06
57,4111307.0,Re-installation/Construction of Regulator/ Ca...,181.80,1333.20,0.0,1515.0,CAP_8,CAP_8,1.27
58,4111307.0,Installation/Construction of New Regulators/ ...,2437.32,17873.68,0.0,20311.0,CAP_8,CAP_8,17.09
59,4111307.0,Re-excavation of Khal/River (New Haors),1167.48,8561.52,0.0,9729.0,CAP_8,CAP_8,8.19
60,4111201.0,Re-excavation of Khal/River (Rehabilitation S...,301.80,2213.20,0.0,2515.0,CAP_8,CAP_8,2.12
61,4111201.0,Rehabilitation of Full Embankment (Resection/...,306.00,2244.00,0.0,2550.0,CAP_8,CAP_8,2.15
62,4111201.0,Rehabilitation of Submergible Embankment (Re...,214.20,1570.80,0.0,1785.0,CAP_8,CAP_8,1.50
63,4111201.0,Construction of Submersible Embankment (New Ha...,1434.30,10518.20,0.0,11952.5,CAP_8,CAP_8,10.06
64,4111201.0,Rehabilitation of Regulator (New Haors),19.92,146.08,0.0,166.0,CAP_8,CAP_8,0.14
65,4111201.0,Construction of WMG Office,165.60,1214.40,0.0,1380.0,CAP_8,CAP_8,1.16
66,4111201.0,O&M During Construction,200.00,0.00,0.0,200.0,CAP_8,CAP_8,0.17

In [68]:
def calcualteCategoryValue(category,df):
    mycat=df[df['Imed']==category]
    Total=0
    for rowindex,row in mycat.iterrows():
        Total=Total+row['TOTAL']
        
    return Total

In [69]:
mytotal=calcualteCategoryValue('CAP_8',dpp_alloc)
print("category={} total={}".format('CAP_8',mytotal))

category=CAP_8 total=53364.5

In [70]:
imed_expenditure=pd.DataFrame()
imed_exp=imed_head.assign(Dpp_allocation=0)
imed_exp=imed_exp.assign(Cumulative_Last_FY=0)
imed_exp=imed_exp.assign(Target_Current_Fy=0)
imed_exp=imed_exp.assign(Jul=0)
 
imed_exp=imed_exp.assign(Aug=0)
imed_exp=imed_exp.assign(Sep=0)
imed_exp=imed_exp.assign(Oct=0)
imed_exp=imed_exp.assign(Nov=0)
imed_exp=imed_exp.assign(Dec=0)
imed_exp=imed_exp.assign(Jan=0)
imed_exp=imed_exp.assign(Feb=0)
imed_exp=imed_exp.assign(Mar=0)
imed_exp=imed_exp.assign(Apr=0)
imed_exp=imed_exp.assign(May=0)
imed_exp=imed_exp.assign(Jun=0)
imed_exp=imed_exp.assign(Jul_Sep_Q1=0)
imed_exp=imed_exp.assign(Oct_Dec_Q2=0)
imed_exp=imed_exp.assign(Jan_Mar_Q3=0)
imed_exp=imed_exp.assign(Apr_Jun_Q4=0)
#imed_exp

for rowindex,row in imed_exp.iterrows():
    total_alloc=calcualteCategoryValue(row['Identifier'],dpp_alloc)
    #total_alloc    
    #print(total_alloc)
    imed_exp.at[rowindex,'Dpp_allocation']=total_alloc    
    
imed_exp

,SLNo,Name of the Component,Type,Identifier,Dpp_allocation,Cumulative_Last_FY,Target_Current_Fy,Jul,Aug,Sep,...,Jan,Feb,Mar,Apr,May,Jun,Jul_Sep_Q1,Oct_Dec_Q2,Jan_Mar_Q3,Apr_Jun_Q4
0,1,Allowances,REV,REV_1,160,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Travel expences,REV,REV_2,100,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Office rent for PMO,REV,REV_3,245,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Misc. taxes,REV,REV_4,2596,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,"Postage, telephone, Internate, Fax, telex etc.",REV,REV_5,75,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,Registration Fees (Vehicles),REV,REV_6,15,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,Water & Elecricity,REV,REV_7,25,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8,Gas & Fuel and Petrol & Lubricant,REV,REV_8,350,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,Insurance/Bank Charges (incl.Veh.),REV,REV_9,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,Printing & Binding,REV,REV_10,35,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,11,Stationary,REV,REV_11,150,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,12,Books & periodical,REV,REV_12,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,13,Overseas Training,REV,REV_13,238,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,14,Local Training,REV,REV_14,4253,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,15,Casual labour/Job worker,REV,REV_15,15,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,16,Consumable Stores,REV,REV_16,25,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,17,Consultancy,REV,REV_17,7901,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,18,Honorarium/Fees/ Remuneration,REV,REV_18,45,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,19,Survey,REV,REV_19,162,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,20,Computer Consumables,REV,REV_20,50,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,21,Other expenses,REV,REV_21,1700,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,22,"Repair & Maintenance of Vehicles, furniture, c...",REV,REV_22,627,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,1,Motor Vehicle,CAP,CAP_1,770,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,2,Water Transport,CAP,CAP_2,100,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,3,Machinary & other equipment,CAP,CAP_3,13,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,4,Engineering equipment,CAP,CAP_4,76,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,5,Computer & Accessories,CAP,CAP_5,38,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,6,Furniture & fixture and Aircooler,CAP,CAP_6,65,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,7,Land acquisition,CAP,CAP_7,24000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8,Construction Works,CAP,CAP_8,53364,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [80]:
dpp_to_imed

      Eocde                                        Description Imedcode
0   3111302                               Conveyance Allowance    REV_1
1   3111327                                 Overtime Allowance    REV_1
2   3111338                                    Other Allowance    REV_1
3   3241101            Travel Expenses (TA & DA for PMO & PIU)    REV_2
4   3211129  Rent-Office : Office Accomodation for PMO (3,5...    REV_3
..      ...                                                ...      ...
62  4111201   Rehabilitation of Submergible Embankment  (Re...    CAP_8
63  4111201  Construction of Submersible Embankment (New Ha...    CAP_8
64  4111201            Rehabilitation of Regulator (New Haors)    CAP_8
65  4111201                         Construction of WMG Office    CAP_8
66  4111201                            O&M During Construction    CAP_8

[67 rows x 3 columns]

In [81]:
def createCumulativeDaraframe():
    cum_expenditure=pd.DataFrame()
    cum_expenditure=cum_expenditure.assign(Jul=0)
    cum_expenditure=cum_expenditure.assign(Aug=0)
    cum_expenditure=cum_expenditure.assign(Sep=0)
    cum_expenditure=cum_expenditure.assign(Oct=0)
    cum_expenditure=cum_expenditure.assign(Nov=0)
    cum_expenditure=cum_expenditure.assign(Dec=0)
    cum_expenditure=cum_expenditure.assign(Jan=0)
    cum_expenditure=cum_expenditure.assign(Feb=0)
    cum_expenditure=cum_expenditure.assign(Mar=0)
    cum_expenditure=cum_expenditure.assign(Apr=0)
    cum_expenditure=cum_expenditure.assign(May=0)
    cum_expenditure=cum_expenditure.assign(Jun=0)
    cum_expenditure=cum_expenditure.assign(Q1=0)
    cum_expenditure=cum_expenditure.assign(Q2=0)
    cum_expenditure=cum_expenditure.assign(Q3=0)
    cum_expenditure=cum_expenditure.assign(Q4=0)    
    #cum_expenditure
    return cum_expenditure

In [82]:
root=Tk()
mypath=filedialog.askopenfilename(title="Monthly Expenditure File",initialdir="/",filetypes=(("xlsx","*.xlsx"),("all types","*.*")))
root.destroy()
mypath
monthly_data_gob=pd.read_excel(mypath,sheet_name="Monthly_19_20_GOB")
monthly_data_gob.fillna(0,inplace=True)
monthly_data_rpa=pd.read_excel(mypath,sheet_name="Monthly_19_20_RPA")
monthly_data_rpa.fillna(0,inplace=True)

#monthly_data.fillna(0,inplace=True)
#code=list(dpp_to_imed['Imedcode'])
#code
#monthly_data.assign(Imed,code)
monthly_data_gob

,Code,Description,Imed_Code,Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb,Mar,Apr,May,Jun
0,3111302,Conveyance Allowance,REV_1,0.0,4650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3111327,Overtime Allowance,REV_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3111338,Other Allowance,REV_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3241101,Travel Expenses (TA & DA for PMO & PIU),REV_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3211129,"Rent-Office : Office Accomodation for PMO (3,5...",REV_3,0.0,655661.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,3821103,"Misc. Taxes (Income Tax of Consultants, Outsou...",REV_4,0.0,766742.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,3211119,Postage,REV_5,0.0,1438.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,3211120,Telephones/Telegram/Teleprinter,REV_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,3211117,Telex/Fax/Internet,REV_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3221104,Registration Fee (Vehicles),REV_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,3211115,Water,REV_7,0.0,2820.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,3211113,Electricity,REV_7,0.0,37257.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,3243102,Gas & Fuel,REV_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,3243101,Petrol and Lubricant,REV_8,0.0,129500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,3221108,Insurance/Bank Charges (including Vehicles),REV_9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,3255102,Printing & Binding,REV_10,0.0,14000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,3255104,"Stationery, Seals & Stamps",REV_11,0.0,49597.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,3211127,Books & Periodicals,REV_12,0.0,575.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,3231201,Overseas Training Course(08 Trainees) & Overse...,REV_13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,3231201,Local Training for (a) O&M manual (For BWDB Of...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,3231201,Agriculture Promotion Support Sub-project (APS...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,3231201,Small Scale Income Generation Sub-project (SIG...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,3211109,Casual labour/Job worker,REV_15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,3256103,Consumable Stores,REV_16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,3257101,Consultancy : International - 71 M/M ...,REV_17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,3111332,a) Honorarium/Fees/Remuneration (for different...,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,3111332,b) Interim Evaluation,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,3111332,c) Progress Monitoring,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,3257104,Survey,REV_19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,3255101,Computer Consumables,REV_20,0.0,13365.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,3258105,Engineering Equipments,REV_22,0.0,5650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,3258114,Repair/Replacement of Regulator Gates and oth...,REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,3258128,Water Transport : Repair of Speedboat(s),REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,3258107,Others : Repair & Maintenance,REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,4112101,Jeep (above 2500 c.c. made by Pragati) -1 No.f...,CAP_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,4112101,"Motorcycle - 35 Nos. (PMO 2 Nos.,Kishoreganj 1...",CAP_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,4112102,Speed Boat with Engine and all accessories (75...,CAP_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,4112316,"Photocopier -7 nos (PMO 2 Nos.,Kishoreganj 1 N...",CAP_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,4112316,"Fax -7 nos (PMO 2 Nos.,Kishoreganj 1 No., Netr...",CAP_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,4112304,Survey Equipments (Digital leveling Instrument...,CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,4112304,"Networking Equipment- 6 nos (PMO 1 No., Kishor...",CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,4112304,Engineering Laboratory Equipments for Kishoreg...,CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,4112202,Desktop Computer- 30 nos. (Project Management...,CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,4112202,"Laptop Computer -11 nos (PMO 6 Nos.,Kishoregan...",CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,4112202,A3 Combo Printer 2 no ( PMO),CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,4112202,"Laser Printer- 11 nos. (PMO 6 Nos.,Kishoreganj...",CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,4112314,Furnitures & Fixtures,CAP_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,4112303,Aircooler,CAP_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,4141101,Land Acquisition ( 470 hectare),CAP_7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,4111306,Construction of Irrigation Inlet (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,4111307,Re-installation/Construction of Regulator/ Ca...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,4111307,Installation/Construction of New Regulators/ ...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,4111307,Re-excavation of Khal/River (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,4111201,Re-excavation of Khal/River (Rehabilitation S...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,4111201,Rehabilitation of Full Embankment (Resection/...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,4111201,Rehabilitation of Submergible Embankment (Re...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,4111201,Construction of Submersible Embankment (New Ha...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,4111201,Rehabilitation of Regulator (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,4111201,Construction of WMG Office,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,4111201,O&M During Construction,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [83]:
def consolidateValue(df,col_index,imed_code):   
    mycat=df.loc[df['Imed_Code']==imed_code]
    #mycat=mycat.iloc[:,col_index]
    #print(mycat)
    Total=0
    for rowindex,row in mycat.iterrows():
        Total += row[col_index]
    return Total

In [84]:
def getEcodeForImedcat(category):
    ecodes=dpp_to_imed[dpp_to_imed['Imedcode']==category]
    return ecodes

In [85]:
monthly_data_rpa

,Code,Description,Imed_Code,Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb,Mar,Apr,May,Jun
0,3111302,Conveyance Allowance,REV_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3111327,Overtime Allowance,REV_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3111338,Other Allowance,REV_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3241101,Travel Expenses (TA & DA for PMO & PIU),REV_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3211129,"Rent-Office : Office Accomodation for PMO (3,5...",REV_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,3821103,"Misc. Taxes (Income Tax of Consultants, Outsou...",REV_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,3211119,Postage,REV_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,3211120,Telephones/Telegram/Teleprinter,REV_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,3211117,Telex/Fax/Internet,REV_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3221104,Registration Fee (Vehicles),REV_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,3211115,Water,REV_7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,3211113,Electricity,REV_7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,3243102,Gas & Fuel,REV_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,3243101,Petrol and Lubricant,REV_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,3221108,Insurance/Bank Charges (including Vehicles),REV_9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,3255102,Printing & Binding,REV_10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,3255104,"Stationery, Seals & Stamps",REV_11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,3211127,Books & Periodicals,REV_12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,3231201,Overseas Training Course(08 Trainees) & Overse...,REV_13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,3231201,Local Training for (a) O&M manual (For BWDB Of...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,3231201,Agriculture Promotion Support Sub-project (APS...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,3231201,Small Scale Income Generation Sub-project (SIG...,REV_14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,3211109,Casual labour/Job worker,REV_15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,3256103,Consumable Stores,REV_16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,3257101,Consultancy : International - 71 M/M ...,REV_17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,3111332,a) Honorarium/Fees/Remuneration (for different...,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,3111332,b) Interim Evaluation,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,3111332,c) Progress Monitoring,REV_18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,3257104,Survey,REV_19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,3255101,Computer Consumables,REV_20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,3258105,Engineering Equipments,REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,3258114,Repair/Replacement of Regulator Gates and oth...,REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,3258128,Water Transport : Repair of Speedboat(s),REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,3258107,Others : Repair & Maintenance,REV_22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,4112101,Jeep (above 2500 c.c. made by Pragati) -1 No.f...,CAP_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,4112101,"Motorcycle - 35 Nos. (PMO 2 Nos.,Kishoreganj 1...",CAP_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,4112102,Speed Boat with Engine and all accessories (75...,CAP_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,4112316,"Photocopier -7 nos (PMO 2 Nos.,Kishoreganj 1 N...",CAP_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,4112316,"Fax -7 nos (PMO 2 Nos.,Kishoreganj 1 No., Netr...",CAP_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,4112304,Survey Equipments (Digital leveling Instrument...,CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,4112304,"Networking Equipment- 6 nos (PMO 1 No., Kishor...",CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,4112304,Engineering Laboratory Equipments for Kishoreg...,CAP_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,4112202,Desktop Computer- 30 nos. (Project Management...,CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,4112202,"Laptop Computer -11 nos (PMO 6 Nos.,Kishoregan...",CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,4112202,A3 Combo Printer 2 no ( PMO),CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,4112202,"Laser Printer- 11 nos. (PMO 6 Nos.,Kishoreganj...",CAP_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,4112314,Furnitures & Fixtures,CAP_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,4112303,Aircooler,CAP_6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,4141101,Land Acquisition ( 470 hectare),CAP_7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,4111306,Construction of Irrigation Inlet (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,4111307,Re-installation/Construction of Regulator/ Ca...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,4111307,Installation/Construction of New Regulators/ ...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,4111307,Re-excavation of Khal/River (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,4111201,Re-excavation of Khal/River (Rehabilitation S...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,4111201,Rehabilitation of Full Embankment (Resection/...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,4111201,Rehabilitation of Submergible Embankment (Re...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,4111201,Construction of Submersible Embankment (New Ha...,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,4111201,Rehabilitation of Regulator (New Haors),CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65,4111201,Construction of WMG Office,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66,4111201,O&M During Construction,CAP_8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
cum_expenditure=createCumulativeDaraframe()
cum_expenditure

Empty DataFrame
Columns: [Jul, Aug, Sep, Oct, Nov, Dec, Jan, Feb, Mar, Apr, May, Jun, Q1, Q2, Q3, Q4]
Index: []

In [86]:
def createCumulativeMonthlyExpenditure(df):
    cum_expenditure=createCumulativeDaraframe()
    cum_expenditure['Jul']=df['Jul']
    cum_expenditure['Aug']= cum_expenditure['Jul']+df['Aug']
    cum_expenditure['Sep']= cum_expenditure['Aug']+df['Sep']
    cum_expenditure['Oct']= cum_expenditure['Sep']+df['Oct']
    cum_expenditure['Nov']= cum_expenditure['Oct']+df['Nov']
    cum_expenditure['Dec']= cum_expenditure['Nov']+df['Dec']
    cum_expenditure['Jan']= cum_expenditure['Dec']+df['Jan']
    cum_expenditure['Feb']= cum_expenditure['Jan']+df['Feb']
    cum_expenditure['Mar']= cum_expenditure['Feb']+df['Mar']
    cum_expenditure['Apr']= cum_expenditure['Mar']+df['Apr']
    cum_expenditure['May']= cum_expenditure['Apr']+df['May']
    cum_expenditure['Jun']= cum_expenditure['May']+df['Jun']
    cum_expenditure['Q1']=cum_expenditure['Sep']
    cum_expenditure['Q2']=cum_expenditure['Dec']
    cum_expenditure['Q3']=cum_expenditure['Mar']
    cum_expenditure['Q4']=cum_expenditure['Jun']    
    return cum_expenditure

In [87]:
icode=dpp_to_imed[dpp_to_imed['Imedcode']=='REV_1']  
#imed_head
icodes=list(imed_head.iloc[:,3])
#print(icodes)
n=len(icodes)
values=[i for i in range(n)]
#print(values)
#icodes
months=[('Jul',3),('Aug',4),('Sep',5),('Oct',6),('Nov',7),('Dec',8),
        ('Jan',9),('Feb',10),('Mar',11),('Apr',12),('May',13),('Jun',14)]

for month in months:
    month_index=month[1]
    month_name=month[0]
    #print(month_index)
    monthly_values=[]    
    for code in icodes:     
        #ecodes=getEcodeForImedcat(code)
        #ecodes=dpp_to_imed[dpp_to_imed['Imedcode']==code]    
        #print("cetegory={}".format(code))
        #print("#################################################")
        #print(ecodes)
        #print(code)
        Total_gob=consolidateValue(monthly_data_gob,month_name,code)
        Total_rpa=consolidateValue(monthly_data_rpa,month_index,code)
        Total= Total_gob+ Total_rpa
        #Total=consolidateValue(dpp_alloc,2,code)    
        #print("imed_code={} value={}".format(code,Total))
        monthly_values.append(round(Total/100000.00,2))
        #monthly_values.append(round(Total/100000.00,2))
        #for code in ecodes:
            #print(code[3].values[0])
        #print(ecodes['Imedcode'].values[0])    
        #wcodes=ecodes.iloc[:,0]
        #print(wcodes)
    #print(monthly_values)
    imed_exp[month_name]=monthly_values
#monthly_values

imed_exp

,SLNo,Name of the Component,Type,Identifier,Dpp_allocation,Cumulative_Last_FY,Target_Current_Fy,Jul,Aug,Sep,...,Jan,Feb,Mar,Apr,May,Jun,Jul_Sep_Q1,Oct_Dec_Q2,Jan_Mar_Q3,Apr_Jun_Q4
0,1,Allowances,REV,REV_1,160,0,0,0.0,0.05,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
1,2,Travel expences,REV,REV_2,100,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
2,3,Office rent for PMO,REV,REV_3,245,0,0,0.0,6.56,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
3,4,Misc. taxes,REV,REV_4,2596,0,0,0.0,7.67,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
4,5,"Postage, telephone, Internate, Fax, telex etc.",REV,REV_5,75,0,0,0.0,0.01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
5,6,Registration Fees (Vehicles),REV,REV_6,15,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
6,7,Water & Elecricity,REV,REV_7,25,0,0,0.0,0.40,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
7,8,Gas & Fuel and Petrol & Lubricant,REV,REV_8,350,0,0,0.0,1.29,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
8,9,Insurance/Bank Charges (incl.Veh.),REV,REV_9,3,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
9,10,Printing & Binding,REV,REV_10,35,0,0,0.0,0.14,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
10,11,Stationary,REV,REV_11,150,0,0,0.0,0.50,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
11,12,Books & periodical,REV,REV_12,2,0,0,0.0,0.01,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
12,13,Overseas Training,REV,REV_13,238,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
13,14,Local Training,REV,REV_14,4253,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
14,15,Casual labour/Job worker,REV,REV_15,15,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
15,16,Consumable Stores,REV,REV_16,25,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
16,17,Consultancy,REV,REV_17,7901,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
17,18,Honorarium/Fees/ Remuneration,REV,REV_18,45,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
18,19,Survey,REV,REV_19,162,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
19,20,Computer Consumables,REV,REV_20,50,0,0,0.0,0.13,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
20,21,Other expenses,REV,REV_21,1700,0,0,0.0,30.71,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
21,22,"Repair & Maintenance of Vehicles, furniture, c...",REV,REV_22,627,0,0,0.0,0.22,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
22,1,Motor Vehicle,CAP,CAP_1,770,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
23,2,Water Transport,CAP,CAP_2,100,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
24,3,Machinary & other equipment,CAP,CAP_3,13,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
25,4,Engineering equipment,CAP,CAP_4,76,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
26,5,Computer & Accessories,CAP,CAP_5,38,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
27,6,Furniture & fixture and Aircooler,CAP,CAP_6,65,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
28,7,Land acquisition,CAP,CAP_7,24000,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0
29,8,Construction Works,CAP,CAP_8,53364,0,0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0

In [88]:
cum_expenditure=createCumulativeMonthlyExpenditure(imed_exp)

In [89]:
def writeMonthlyHeading(wb,month,Fy):
    sheet3=wb['Sheet3']
    sheet2=wb['Sheet2']
    sheet1=wb['Sheet1']
    #sheet2.cell(row=2,column=1).value="Prepared by Zaki"

In [141]:
def prepareMonthlyImed(df_cur,df_prev,month,Fy):
    wb=opxl.load_workbook(template_file_monthly)
    sheet3=wb['Sheet3']
    sheet2=wb['Sheet2']
    sheet1=wb['Sheet1']
    sheet2.cell(row=2,column=1).value
    offset=5
    for index,row in df_cur.iterrows():
        if index < 22:
            sheet3.cell(row = index+offset, column = 4).value=df_prev.iloc[index,2]
            sheet3.cell(row = index+offset, column = 6).value=df_prev.iloc[index,4]
            sheet3.cell(row = index+offset, column = 8).value=row[month]
            
            #rev=df_prev.iloc[row,'pp_alloc']
            #rev[0]
            #rev[1]
            #hysical=(row[month]/df_prev.iloc[i0])*df_prev.iloc[row,1]
            #physical=(row[month]/df_prev.iloc[index,0])*df_prev.iloc[index,1]
            #sheet3.cell(row = index+offset, column = 9).value=physical/100.00
        else:
            sheet3.cell(row = index+offset+2, column = 4).value=df_prev.iloc[index,2]
            sheet3.cell(row = index+offset+2, column = 6).value=df_prev.iloc[index,4]
            sheet3.cell(row = index+offset+2, column = 8).value=row[month]
            #physical=(row[month]/df_prev.iloc[index,0])*df_prev.iloc[index,1]            
            #sheet3.cell(row = index+offset+2, column = 9).value=physical/100.00
            
        #print("index={} expenditure={}".format(index,row[month]))
    """          
    offset=5
    for index,row in df_prev.iterrows():
         #	Fin_prev 	Phy_prev 	Fin_curr 	Phy_curr
        if index < 22:
            sheet3.cell(row = index+offset, column = 4).value=row['Fin_prev']
            #sheet3.cell(row = index+offset, column = 5).value=row['Phy_prev']/100.0
            sheet3.cell(row = index+offset, column = 6).value=row['Fin_curr']
            #sheet3.cell(row = index+offset, column = 7).value=row['Phy_curr']/100.0
            
        else:
            sheet3.cell(row = index+offset+3, column = 4).value=row['Fin_prev']
            #sheet3.cell(row = index+offset+2, column = 5).value=row['Phy_prev']/100.0
            sheet3.cell(row = index+offset+3, column = 6).value=row['Fin_curr']
            #sheet3.cell(row = index+offset, column = 7).value=row['Phy_curr']/100.0
            
        #print("index={} expenditure={}".format(index,row[month]))
    """
    #wrting heading data
    #writeMonthlyHeading(wb,month,Fy)
    root=Tk()    
    save_filename = filedialog.asksaveasfilename(title='Imed Report filename',defaultextension = 'xlsx',initialdir = "/");
    root.destroy()
    wb.save(save_filename)

In [112]:
cum_expenditure

,Jul,Aug,Sep,Oct,Nov,Dec,Jan,Feb,Mar,Apr,May,Jun,Q1,Q2,Q3,Q4
0,0.0,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05
1,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.0,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56,6.56
3,0.0,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67,7.67
4,0.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
5,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,0.0,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40
7,0.0,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29,1.29
8,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
9,0.0,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14,0.14
10,0.0,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50,0.50
11,0.0,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
12,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
14,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
16,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
17,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
18,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
19,0.0,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13,0.13
20,0.0,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71,30.71
21,0.0,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22,0.22
22,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
23,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
24,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
26,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
27,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
28,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
29,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [113]:
#wb=opxl.load_workbook(template_file_monthly)
#sheet3=wb['Sheet3']
#sheet2=wb['Sheet2']
#sheet1=wb['Sheet1']
#offset=5
#sheet3.cell(row = offset, column = 8).value=cum_expenditure.iloc[0,11]
#root=Tk()
#mypath=filedialog.(title="Monthly Expenditure File",initialdir="/",filetypes=(("xlsx","*.xlsx"),("all types","*.*")))
#save_filename = filedialog.asksaveasfilename(title='Imed Report filename',defaultextension = 'xlsx',initialdir = "/");
#root.destroy()
#wb.save(save_filename)

In [114]:
def createPrevData(dpp_alloc,weight,finan_prev,phy_prev,finan_curr,phy_curr):
    df=pd.DataFrame()
    df=df.assign(Dpp_alloc=dpp_alloc)
    df=df.assign(Weight=weight)
    df=df.assign(Fin_prev=finan_prev)
    df=df.assign(Phy_prev=phy_prev)
    df=df.assign(Fin_curr=finan_curr)
    df=df.assign(Phy_curr=phy_curr)
    return df

In [137]:
root=Tk()
mypath=filedialog.askopenfilename(title="Prevoius Year Data",initialdir="/",filetypes=(("xlsx","*.xlsx"),("all types","*.*")))
root.destroy()
mypath
previous_data=pd.read_excel(mypath,sheet_name='Prev_Data',index_col=None,header=0)
previous_data.fillna(0,inplace=True)
mydata=previous_data[previous_data['Imed_Code']=='CAP_8']
mydata

,Code,Description,Imed_Code,Dpp_allocation,Weight,Prev_Progress_Fin,Prev_Progress_Phy,Cur_Tar_Fin,Cur_Tar_Phy
56,4111306,Construction of Irrigation Inlet (New Haors),CAP_8,1261.0,1.06,116.72,0.098115,490.33,0.412173
57,4111307,Re-installation/Construction of Regulator/ Ca...,CAP_8,1515.0,1.27,0.00,0.000000,0.00,0.000000
58,4111307,Installation/Construction of New Regulators/ ...,CAP_8,20311.0,17.09,6143.66,5.169374,8105.58,6.820165
59,4111307,Re-excavation of Khal/River (New Haors),CAP_8,9729.0,8.19,6011.48,5.060543,3956.08,3.330280
60,4111201,Re-excavation of Khal/River (Rehabilitation S...,CAP_8,2515.0,2.12,455.04,0.383572,900.73,0.759263
61,4111201,Rehabilitation of Full Embankment (Resection/...,CAP_8,2550.0,2.15,452.46,0.381486,913.26,0.770004
62,4111201,Rehabilitation of Submergible Embankment (Re...,CAP_8,1785.0,1.50,341.85,0.287269,657.55,0.552563
63,4111201,Construction of Submersible Embankment (New Ha...,CAP_8,11952.5,10.06,6127.06,5.156931,4914.31,4.136202
64,4111201,Rehabilitation of Regulator (New Haors),CAP_8,166.0,0.14,73.26,0.061786,0.00,0.000000
65,4111201,Construction of WMG Office,CAP_8,1380.0,1.16,42.09,0.035380,318.14,0.267422
66,4111201,O&M During Construction,CAP_8,200.0,0.17,0.00,0.000000,0.00,0.000000

In [142]:
value=consolidateValue(previous_data,5,'REV_1')
value
dpp_alloc=[]
weight=[]
physical_prev=[]
financial_prev=[]
physical_cur=[]
financial_cur=[]

icodes=list(imed_head.iloc[:,3])
for code in icodes:
    value1=consolidateValue(previous_data,5,code)
    value2=consolidateValue(previous_data,6,code)
    value3=consolidateValue(previous_data,7,code)
    value4=consolidateValue(previous_data,8,code)
    value5=consolidateValue(previous_data,3,code)
    value6=consolidateValue(previous_data,4,code)
    financial_prev.append(value1)
    physical_prev.append(value2)
    financial_cur.append(value3)
    physical_cur.append(value4)
    dpp_alloc.append(value5)
    weight.append(value6)
    
    
prev_year_data=createPrevData(dpp_alloc,weight,financial_prev,physical_prev,financial_cur,physical_cur)
prev_year_data
#cum_expenditure
prepareMonthlyImed(cum_expenditure,prev_year_data,'Jun','2018-2019')